<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_carrier_NameComp_select</name>
   <tag></tag>
   <elementGuidId>b445f19e-6464-499e-9173-91495091a0b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ddlShippingCarrier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ContentPlaceHolder1_ddlShippingCarrier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1d7f5def-4ac8-4a2d-88b7-1acb6a6acf11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ddlShippingCarrier</value>
      <webElementGuid>3a1e4865-95e1-4cce-88c5-f2142548c800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$ContentPlaceHolder1$ddlShippingCarrier\',\'\')', 0)</value>
      <webElementGuid>94fdffcc-d9dd-4a7d-a74a-f672d2eb17b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ddlShippingCarrier</value>
      <webElementGuid>b0223740-8f2e-4c1b-b2cc-3da0a2489b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			Select
			Amazon
			DHL
			DHLGM
			Fedex
			Generic
			LTL
			Other
			SellerCloud
			UPS
			USPS

		</value>
      <webElementGuid>26189f0b-9e8e-4a70-8db0-52b6cd8e5bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ddlShippingCarrier&quot;)</value>
      <webElementGuid>dd9dad4a-2d0b-415e-8b05-fbca3619db62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ContentPlaceHolder1_ddlShippingCarrier']</value>
      <webElementGuid>4db00233-289e-4963-b3e2-8d3c72f8aea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlCreateOrder']/table/tbody/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>74ae285c-3232-4245-8e1b-0d9d5fcddf41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carrier:'])[1]/following::select[1]</value>
      <webElementGuid>6ebe7531-ef20-45a4-b274-206a6e436ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Method'])[1]/following::select[1]</value>
      <webElementGuid>1d88d6d6-b068-4487-9257-b86d3c716b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Method:'])[1]/preceding::select[1]</value>
      <webElementGuid>5a1cc8ef-9180-48f3-9d30-a9ac0ee39320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lock shipping method'])[1]/preceding::select[2]</value>
      <webElementGuid>1c73ee81-d3dd-4138-873b-1319f316bf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>075d1ae7-dea3-448d-bfaa-59be97fd6479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder1$ddlShippingCarrier' and @id = 'ContentPlaceHolder1_ddlShippingCarrier' and (text() = '
			Select
			Amazon
			DHL
			DHLGM
			Fedex
			Generic
			LTL
			Other
			SellerCloud
			UPS
			USPS

		' or . = '
			Select
			Amazon
			DHL
			DHLGM
			Fedex
			Generic
			LTL
			Other
			SellerCloud
			UPS
			USPS

		')]</value>
      <webElementGuid>8e22fff1-d630-4f50-a8e5-1e00d9792e49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
