<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Check GTprice</name>
   <tag></tag>
   <elementGuidId>bdb566ec-1023-4daf-bf26-a227ebe07952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_GrandTotalField']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_GrandTotalField</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8551dab1-ea3a-47dd-b477-17324265c0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_GrandTotalField</value>
      <webElementGuid>511363ac-21e0-444c-a3c2-ee6d4fa72152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$30.60</value>
      <webElementGuid>62eeccd2-8b6f-4484-bc00-58d0acb0f07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_GrandTotalField&quot;)</value>
      <webElementGuid>4fce8ad5-10ca-4128-a145-5c2e0ffeea10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_GrandTotalField']</value>
      <webElementGuid>248cf6e9-05a6-4a25-8d67-34adf1775704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_trMainRow']/td/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[11]/td[2]/b/span</value>
      <webElementGuid>809369c9-5736-477d-85aa-ef4873b17290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grand Total:'])[1]/following::span[1]</value>
      <webElementGuid>bc28d055-e7a8-4517-9a4c-4460d1c18c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[6]/following::span[1]</value>
      <webElementGuid>21d62ed4-fb69-4fad-83ff-6aa31d5c1771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Items'])[1]/preceding::span[1]</value>
      <webElementGuid>d12366c8-d7fe-4c4b-8a44-d5f98762d7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local SKU'])[1]/preceding::span[1]</value>
      <webElementGuid>eea1369b-7043-487f-b7c1-0d0fbc2c61b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b/span</value>
      <webElementGuid>24cdc0f2-d582-42f4-888b-bc7b21c6b0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_GrandTotalField' and (text() = '$30.60' or . = '$30.60')]</value>
      <webElementGuid>047495fe-c376-46ba-9fc4-7f86b7e5b66c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
