<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>change Price</name>
   <tag></tag>
   <elementGuidId>62d94e41-eebc-4ed7-b664-9907e54cdcf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a5085f8-a70d-4b89-9fe9-47b956bf1a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$NonPackageItems$ctl02$AdjustedPriceField</value>
      <webElementGuid>037571c2-844a-4f2d-a859-77e9be86c5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7007e115-a5d3-4808-84fa-db1997cd80ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>bf47bc57-a5d4-4ba2-b4bf-cc4c350da896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0</value>
      <webElementGuid>60745b4a-3d42-49a2-878e-9c074ca134fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0&quot;)</value>
      <webElementGuid>891706bc-adbd-47e1-9592-18c200d29a1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0']</value>
      <webElementGuid>ca620ad3-89de-435c-8f61-6240ab215fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ContentPlaceHolder1_NonPackageItems']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>c6f7c38d-22a6-4192-8fc1-445dd25d8f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>59c4b707-7924-43a7-9589-96399fbf4bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$NonPackageItems$ctl02$AdjustedPriceField' and @type = 'text' and @id = 'ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0']</value>
      <webElementGuid>741a5200-f00b-4923-b748-96a6544ce9e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
