<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductLevelDisc</name>
   <tag></tag>
   <elementGuidId>22633a6c-5fb7-4afe-a3ce-09db26f6eb99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_NonPackageItems_txtdiscountValue_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_NonPackageItems_txtdiscountValue_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5f22cf0-d1c6-429c-a8cf-1142cd6c9d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$NonPackageItems$ctl02$txtdiscountValue</value>
      <webElementGuid>9bb0133f-cdc3-43da-80e4-2a06c19ae6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72d5803f-0528-443c-a6fe-f76eea750cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>36177d4c-d57b-42e8-a2ea-e40a227a9131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_NonPackageItems_txtdiscountValue_0</value>
      <webElementGuid>28dcc3d9-4ea1-4c67-b8f7-a1a4d115764b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_NonPackageItems_txtdiscountValue_0&quot;)</value>
      <webElementGuid>d977f008-f104-48ce-82f3-23ae3ffe16ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_NonPackageItems_txtdiscountValue_0']</value>
      <webElementGuid>bafad938-4191-4e71-b326-41956e8de090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ContentPlaceHolder1_NonPackageItems']/tbody/tr[2]/td[12]/input</value>
      <webElementGuid>50d17052-6fc6-4431-a3be-14e3bd9404f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/input</value>
      <webElementGuid>992dbc08-0e1d-47e6-a584-7760c6af8226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$NonPackageItems$ctl02$txtdiscountValue' and @type = 'text' and @id = 'ContentPlaceHolder1_NonPackageItems_txtdiscountValue_0']</value>
      <webElementGuid>d313d292-d993-48c0-8d66-fe5026395a5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
