<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_productQty</name>
   <tag></tag>
   <elementGuidId>0ddd9a2d-f760-44db-ba3d-a4f02a7d4882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_NonPackageItems_QtyField_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_NonPackageItems_QtyField_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d98319cd-7895-465f-a7bf-6b814dac1c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$NonPackageItems$ctl02$QtyField</value>
      <webElementGuid>aaf78aa5-18f2-46a9-ab43-2bbd6c1beedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d7ea237-55a5-491a-8f4f-0ccd4c5b6156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>23f4292a-0292-4029-a315-0dcad58e7c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_NonPackageItems_QtyField_0</value>
      <webElementGuid>61746b1b-e963-43d6-9a8b-76b72168d545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_NonPackageItems_QtyField_0&quot;)</value>
      <webElementGuid>a1148ce3-5df4-4dc4-8f5e-e388cde514d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_NonPackageItems_QtyField_0']</value>
      <webElementGuid>67d7cf67-2ffc-4d92-8ed7-b4541173fd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ContentPlaceHolder1_NonPackageItems']/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>282ae1d7-79a3-4a36-b09d-35d4f921d115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>5b5651de-efcf-46d6-8da5-c8493e52eba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$NonPackageItems$ctl02$QtyField' and @type = 'text' and @id = 'ContentPlaceHolder1_NonPackageItems_QtyField_0']</value>
      <webElementGuid>e52ff794-c526-4bc0-94af-8f38554b1d5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
