<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_unitprice</name>
   <tag></tag>
   <elementGuidId>83665e11-711f-48e0-8291-3d73d7002c49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c26a918-622b-41fb-a253-f68428751967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$NonPackageItems$ctl02$AdjustedPriceField</value>
      <webElementGuid>6a88b34f-e54a-400e-9ca7-c46b31428bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a93744e-4423-43d6-bc56-caeba674432e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>9e96fd2d-d85f-4028-a578-7e12f57f63ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0</value>
      <webElementGuid>c85402e8-c471-41cd-96b7-e3c4fbf8181e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0&quot;)</value>
      <webElementGuid>54fa1d13-74c1-49f9-ad5a-796597f2ec50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0']</value>
      <webElementGuid>e15a379b-e633-410c-9a80-3aa26dd0e06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ContentPlaceHolder1_NonPackageItems']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>6fdededa-f92f-4173-9825-2363323f5d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>71620c56-b753-4e42-96b2-68db8b1ddf3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$NonPackageItems$ctl02$AdjustedPriceField' and @type = 'text' and @id = 'ContentPlaceHolder1_NonPackageItems_AdjustedPriceField_0']</value>
      <webElementGuid>043371ce-e53d-49d7-87ad-e421936959f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
