<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EditCompanyName</name>
   <tag></tag>
   <elementGuidId>921735e2-8893-473d-815b-396a71d8ae96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_BillingAddress_CompanyField']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_BillingAddress_CompanyField</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4542fa5d-05f5-4ede-86a2-5fa9d7321caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$BillingAddress$CompanyField</value>
      <webElementGuid>a9315a33-0550-48d8-838a-f4e381c936e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eac8005e-cc25-40ac-893f-6e2577379bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>testing co</value>
      <webElementGuid>4ae0c39d-d8e9-43f1-b1b3-248d89aca779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>51d0ef04-89da-4ad1-924f-67e6f04397fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_BillingAddress_CompanyField</value>
      <webElementGuid>c7653f47-7be5-4ae2-a6a9-a6cd598e5c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_BillingAddress_CompanyField&quot;)</value>
      <webElementGuid>cab6c889-af60-41e2-bc80-13c5bc8dfa5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_BillingAddress_CompanyField']</value>
      <webElementGuid>81776ab8-c835-46d3-b385-033a4cbf224a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_BillingAddress_trCompany']/td[2]/input</value>
      <webElementGuid>c585ede4-faa8-41d0-8fa3-7318b6b1aaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>375fc26b-047b-490f-9e6a-800a3454b052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$BillingAddress$CompanyField' and @type = 'text' and @id = 'ContentPlaceHolder1_BillingAddress_CompanyField']</value>
      <webElementGuid>0e993266-46ca-4771-bcf3-f4ac28ec8726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
