<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GoActionBtn</name>
   <tag></tag>
   <elementGuidId>0b45921b-15a5-4293-9fc3-3a5c99376532</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ImageButton1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ImageButton1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2788e4db-a070-4d7f-877e-5149a77ef27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>172f6ce8-5465-4aba-b049-da8383e0fcf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ImageButton1</value>
      <webElementGuid>921caf49-e9db-4d1c-a368-3026979c8958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ImageButton1</value>
      <webElementGuid>c967b3cb-b672-4f1c-a704-f5addf6e5f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/app/go-button.gif</value>
      <webElementGuid>752ea74a-e14d-4a3d-b309-6317f4a27478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return ConfirmAction(this);</value>
      <webElementGuid>d5271460-54a0-46fe-8872-19be00987ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ImageButton1&quot;)</value>
      <webElementGuid>407d014d-e294-4893-8882-ca3647d734e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ImageButton1']</value>
      <webElementGuid>168116f0-a1bd-4c01-a4ef-b46cc6d4d4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/table/tbody/tr[4]/td[2]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>f335ca21-9bf8-483d-ba30-dd94097ac0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>6dfc31f4-90fe-4a2d-90f4-336a854f3e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$ImageButton1' and @id = 'ContentPlaceHolder1_ImageButton1' and @src = '/images/app/go-button.gif']</value>
      <webElementGuid>f6513511-2e53-4c1e-9c31-518ffcd937f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
