<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UnitPrice_InORD</name>
   <tag></tag>
   <elementGuidId>e2610e2d-3ea6-4d16-9457-a5bd808cdb3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29331124-6d11-46ce-9906-da427f919644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl04$txtPrice</value>
      <webElementGuid>76552053-5f03-4b4d-88c2-3e1476fa447e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00c22f47-4620-4661-8d1a-ec0d006d7109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9ef9b4b3-effe-43c0-bd46-f547d4de92b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice</value>
      <webElementGuid>e3ff4958-02a6-43ab-a0be-dff47c0c1b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>adjustSubtotal('ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice', 'ContentPlaceHolder1_grdMain_ctl00_ctl04_txtQty', 'ContentPlaceHolder1_grdMain_ctl00_ctl04_lblSubTotal');</value>
      <webElementGuid>ecb644cc-b814-4540-8178-6bfc1c17cce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice&quot;)</value>
      <webElementGuid>e7656969-a9be-484e-b5e0-e9116a82394a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice']</value>
      <webElementGuid>0e5bd862-5997-483a-be95-1d2a79620390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdMain_ctl00__0']/td[5]/input</value>
      <webElementGuid>33a117d4-748a-43f8-84d1-a4065fdadeb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/table/tbody/tr/td[5]/input</value>
      <webElementGuid>0a77dc9e-825c-4872-bfa4-899cf2765ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl04$txtPrice' and @type = 'text' and @id = 'ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice']</value>
      <webElementGuid>26202280-0dc2-462d-9a46-ec6e9f9b4e50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
