<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnProcessJob</name>
   <tag></tag>
   <elementGuidId>5a23d7c7-df24-4097-9623-b6cd0e3868fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90ed205c-a149-40b3-889e-98cd835f7b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>26e76e52-67d3-47d5-b683-56d87e07158b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ContentPlaceHolder1$ContentPlaceHolder1$QueuedJobDetail1$btnProcessJob</value>
      <webElementGuid>2dd53ec4-b35b-4d74-a406-e6e46ac80536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Process Job</value>
      <webElementGuid>a1c15ac2-8193-4bb3-b78a-637f98e07042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hideMe(this);</value>
      <webElementGuid>b95ce7aa-fd3a-490b-a7ff-517ff50542e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob</value>
      <webElementGuid>3f45c74c-bcb4-489e-bc73-16729a02016f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob&quot;)</value>
      <webElementGuid>0814308c-58e8-4705-9b43-653027392afc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob']</value>
      <webElementGuid>e5b5b2e6-9a93-4535-ae84-a7631a13d067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_trProcessJob']/td/input</value>
      <webElementGuid>2a5eb691-689c-445d-a3ca-49cd1a2abef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/div/table/tbody/tr/td/input</value>
      <webElementGuid>e23f76a6-86d1-4c07-bf91-6f1137454b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ctl00$ContentPlaceHolder1$ContentPlaceHolder1$QueuedJobDetail1$btnProcessJob' and @id = 'ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob']</value>
      <webElementGuid>2578794c-8aac-4b47-a194-dd7dd96f3139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
