<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_selectOrd5</name>
   <tag></tag>
   <elementGuidId>9e2c710c-f351-417c-a7dc-1c0757da02e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl16_columnSelectCheckBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdMain_ctl00_ctl16_columnSelectCheckBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6c024f0-7ebd-4380-b06d-46b4459f88b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdMain_ctl00_ctl16_columnSelectCheckBox</value>
      <webElementGuid>4ec9bee1-6c83-446b-9b4a-e386d579df1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6c2c7eed-9326-40eb-bc47-70f67cbb84a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl16$columnSelectCheckBox</value>
      <webElementGuid>401bfdde-eb83-4203-9fff-eaf1b520e7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdMain_ctl00_ctl16_columnSelectCheckBox&quot;)</value>
      <webElementGuid>1cb5369b-7438-4a7a-8d00-4e109b342a43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl16_columnSelectCheckBox']</value>
      <webElementGuid>c18df7ca-baa9-42d3-b883-0fe584d20966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdMain_ctl00__4']/td[3]/input</value>
      <webElementGuid>bde461da-d011-4315-a5c3-7d85df6074f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[3]/input</value>
      <webElementGuid>1999b748-759a-4e18-8cb0-9735d5d08bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_grdMain_ctl00_ctl16_columnSelectCheckBox' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl16$columnSelectCheckBox']</value>
      <webElementGuid>5fa7a000-879d-43f1-be31-d0527b1dd6d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
