<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnSearch</name>
   <tag></tag>
   <elementGuidId>563da426-6cc9-4aab-b2b3-5325978f57ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_btnSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_btnSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e8b1397-ee42-4e67-9c68-005dd37cb759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>24c7c3bb-8941-455d-8526-614d411d619b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$btnSearch</value>
      <webElementGuid>e2376f30-d0fa-4465-9da8-04198f3c2ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_btnSearch</value>
      <webElementGuid>aa59d6c6-3e67-4cd6-acc0-1af9afcca597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/app/search-button.jpg</value>
      <webElementGuid>74029b1a-cc65-42a4-9fe0-b391afe81d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_btnSearch&quot;)</value>
      <webElementGuid>72fed720-b311-4eb5-abf3-826464b6f8c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_btnSearch']</value>
      <webElementGuid>a13d4e2a-23e2-4eeb-a03e-9e12f480450f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlSearchButtons']/table/tbody/tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>965c7021-2f7f-46b5-85d0-d38ddfdef1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>094ca6c8-22f7-4e8b-aeeb-8aabe16c3798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$btnSearch' and @id = 'ContentPlaceHolder1_btnSearch' and @src = '/images/app/search-button.jpg']</value>
      <webElementGuid>6a5e794f-15f2-4c2b-beaa-75b32d8fcdab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
