<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ContinueGenerateBtn</name>
   <tag></tag>
   <elementGuidId>faac9191-ac1b-404e-b796-8f22db3f4066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_btnContinueGenerate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_btnContinueGenerate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c766e13-5444-48b9-b745-39210dce7921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0051083-8454-4c0d-8f2d-ba748d6ee29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$btnContinueGenerate</value>
      <webElementGuid>20f0ef6f-d097-4faf-8167-ad9dd35dc893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue Generate Pick List</value>
      <webElementGuid>15f24054-8ff1-4f66-b4fc-2afc05a7f3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hideButton(this);__doPostBack('ctl00$ContentPlaceHolder1$btnContinueGenerate','')</value>
      <webElementGuid>1efebcd2-8b69-4833-a448-bdb5e17f09b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_btnContinueGenerate</value>
      <webElementGuid>72a11a34-ced1-435e-8363-c3d079eeab5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_btnContinueGenerate&quot;)</value>
      <webElementGuid>ecf60226-c947-4964-a094-8a3dff905afe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_btnContinueGenerate']</value>
      <webElementGuid>37ceab46-c22c-4ed1-8237-bbaf5f77dd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlMain']/p/input</value>
      <webElementGuid>32f5f52b-be45-41b0-9c99-a5deb872368e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>1f6757f8-fe93-4b49-92de-4b7297a90642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'ctl00$ContentPlaceHolder1$btnContinueGenerate' and @id = 'ContentPlaceHolder1_btnContinueGenerate']</value>
      <webElementGuid>bbe9c6a5-0f28-431b-8f85-d46352960853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
