<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_selectOrd2</name>
   <tag></tag>
   <elementGuidId>218fa5d2-9649-4468-b5f7-3961d09d5ee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl07_columnSelectCheckBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdMain_ctl00_ctl07_columnSelectCheckBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2353c4d2-099f-4e55-a82e-d4108754db75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdMain_ctl00_ctl07_columnSelectCheckBox</value>
      <webElementGuid>42e9319a-1ef1-4bc3-b41b-b02d01cb26d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ca6d5fab-c547-4f9c-8674-a3821b8db40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl07$columnSelectCheckBox</value>
      <webElementGuid>e55e0a7b-5247-475b-a626-61ef7f927a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdMain_ctl00_ctl07_columnSelectCheckBox&quot;)</value>
      <webElementGuid>3734d5f7-cea3-4bfb-892c-f0e4e9718f63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl07_columnSelectCheckBox']</value>
      <webElementGuid>fda7d05a-1cf4-4a16-b1b8-cbbbf18f1715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdMain_ctl00__1']/td[3]/input</value>
      <webElementGuid>1dfb2ac0-ec73-43b3-a897-474d196240ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/input</value>
      <webElementGuid>0dc8e237-8fb6-41ac-b8b1-078fdb03d306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_grdMain_ctl00_ctl07_columnSelectCheckBox' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl07$columnSelectCheckBox']</value>
      <webElementGuid>495ae6a6-44b0-47b3-906e-c69e69ce3337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
