<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_picklistDtl</name>
   <tag></tag>
   <elementGuidId>8dcf8daf-a062-4493-bbbd-75c9bb1ceeab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_lblTotalOrders']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_lblTotalOrders</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1d385b66-b545-4cf8-95f3-65ae9be4545a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_lblTotalOrders</value>
      <webElementGuid>7c47bad0-7c8e-4e55-afd5-92a4e7cb6de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total Orders: 2Total Products: 1Total Units: 6</value>
      <webElementGuid>1d6d57df-200c-4c44-92f4-4eaf56e29e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_lblTotalOrders&quot;)</value>
      <webElementGuid>9237ed11-baf6-4a4d-b0f8-06541139c433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_lblTotalOrders']</value>
      <webElementGuid>82eaa208-42af-4862-8cb3-3fe3ade17bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlMainForm']/table/tbody/tr[8]/td/span</value>
      <webElementGuid>a6d78d51-3eec-4d5a-9e3c-08aacc741831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Picked'])[1]/following::span[1]</value>
      <webElementGuid>2a2ea5a6-5a70-4c57-8b28-e2195b8c22c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Picked'])[1]/following::span[1]</value>
      <webElementGuid>9a791fd2-3e0d-405c-b761-2b6fe1cd9533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select all pages'])[1]/preceding::span[1]</value>
      <webElementGuid>5e6365c0-a673-40b9-9fdd-6831ea54fb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show ALL'])[1]/preceding::span[1]</value>
      <webElementGuid>46240310-d2bb-4db9-8940-225f2438f093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Total Orders: 2']/parent::*</value>
      <webElementGuid>05306b9c-b421-4ee5-8b82-611ba5d1b527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/span</value>
      <webElementGuid>5ce47c62-a61d-43e8-be73-306fe305b8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_lblTotalOrders' and (text() = 'Total Orders: 2Total Products: 1Total Units: 6' or . = 'Total Orders: 2Total Products: 1Total Units: 6')]</value>
      <webElementGuid>6a2bdd5e-212c-4331-80be-f7e7d907b7c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
