<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Getshipamount</name>
   <tag></tag>
   <elementGuidId>27f51fc1-a066-4b03-8b1b-c9ae23cca16e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ShippingTotalField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_ShippingTotalField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a60a8cc6-059b-4545-8ca8-98a6c3e1174f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ShippingTotalField</value>
      <webElementGuid>874b9571-bb74-4503-adb1-a0a3a7697a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C$8.00</value>
      <webElementGuid>15077e5a-4899-41fd-8596-055478487f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ShippingTotalField&quot;)</value>
      <webElementGuid>5bf9a002-7b55-4dbf-ae4a-64aae91e7288</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_ShippingTotalField']</value>
      <webElementGuid>0188dc9e-71a5-46ee-b9ea-c6af2b05296e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/table/tbody/tr[4]/td[2]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr[5]/td/table/tbody/tr/td[4]/table/tbody/tr[5]/td[2]/span</value>
      <webElementGuid>5ec7104a-7bdb-4326-abdc-f3868af2b0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping:'])[1]/following::span[1]</value>
      <webElementGuid>a10df107-ff5b-4dfb-8e1f-638e58259ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$3.75'])[2]/following::span[1]</value>
      <webElementGuid>716d2dda-d7fb-4bbd-bf9c-31f866591a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$0.00'])[13]/preceding::span[1]</value>
      <webElementGuid>bf1217e7-2b7a-45ca-b5d5-75076f5c2b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='C$8.00']/parent::*</value>
      <webElementGuid>05191315-9f8d-4612-8c41-e5b3771b534a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr[5]/td[2]/span</value>
      <webElementGuid>7c58c8ef-d0cd-4a0e-954a-814e32bd1ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_ShippingTotalField' and (text() = 'C$8.00' or . = 'C$8.00')]</value>
      <webElementGuid>5d1c7eda-0ac9-43ac-879b-3b56dc34d1ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
