<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Settings</name>
   <tag></tag>
   <elementGuidId>3f31af1e-54b5-443b-b334-ebc8af499a45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mnuMainSettings']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mnuMainSettings</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb0111b5-8fc8-4c20-bcb8-89c4667a1609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rmLink rmRootLink rmExpanded</value>
      <webElementGuid>dbe41fdc-d36e-4e8c-9795-c0e5da9c7d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mnuMainSettings</value>
      <webElementGuid>7b0a8167-1cd5-44e6-838a-e307a6272add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Settings/default.aspx</value>
      <webElementGuid>2bbe106b-d998-44b9-883f-9ed193207f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>0b6af7ea-838f-440c-8796-dc697994f4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mnuMainSettings&quot;)</value>
      <webElementGuid>894c904e-3635-4c34-8204-4236b893f03e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mnuMainSettings']</value>
      <webElementGuid>12eadf6b-47d4-4536-88da-96fdbc2bd785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mnyMain']/ul/li[7]/a</value>
      <webElementGuid>85d5dd9d-8850-441f-9a51-81c1c70a0b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access List'])[1]/following::a[1]</value>
      <webElementGuid>810f6fe5-28e1-4066-b245-1d9f3baeca1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Employee'])[1]/following::a[2]</value>
      <webElementGuid>46522ed0-9c64-486b-b4b2-a00b68c21aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Settings'])[1]/preceding::a[1]</value>
      <webElementGuid>dbab4890-40b2-46a4-ad00-789cac85db2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Settings/default.aspx')]</value>
      <webElementGuid>d17f2c4b-4858-4763-81de-2b3294b56302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>d49f95ab-109e-4ccd-b826-9ac52caf162a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'mnuMainSettings' and @href = 'Settings/default.aspx' and (text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>8b2f2f3b-0417-43ef-aef2-0f26b211898a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
