<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_chkChargeTaxOnShipping</name>
   <tag></tag>
   <elementGuidId>4d6bddfa-4ec9-47fe-bb9f-e0bf31be09af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_chkChargeTaxOnShipping']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_chkChargeTaxOnShipping</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>967b2987-dda3-468e-a8b2-5257b85d25c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_chkChargeTaxOnShipping</value>
      <webElementGuid>12481c4c-956d-4293-b476-49e535e18560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7278d84a-85a6-44c2-a11c-9ecf11846d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$chkChargeTaxOnShipping</value>
      <webElementGuid>8b7e9c5e-55d9-408c-94d8-25c4168adf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>b622621e-19b5-4abb-8451-504205ecf295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_chkChargeTaxOnShipping&quot;)</value>
      <webElementGuid>0a50cbb5-5c0f-47f4-939c-b67cc87cae5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_chkChargeTaxOnShipping']</value>
      <webElementGuid>67386735-6bb9-4f01-a999-3b7e6dfefa64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblShipping']/tbody/tr[5]/td/input</value>
      <webElementGuid>13b6812b-00f6-478e-87a5-dbfe04604341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[2]/td/table/tbody/tr[5]/td/input</value>
      <webElementGuid>4435227b-371b-45bb-95e6-357318ca9c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_chkChargeTaxOnShipping' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$chkChargeTaxOnShipping' and @checked = 'checked']</value>
      <webElementGuid>f5a52f15-31a6-48f8-a0cf-064aaaf264b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
