<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify label_Charge Tax on Shipping</name>
   <tag></tag>
   <elementGuidId>f7d08d9d-dcde-4da5-8ec4-e4f307fbd676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblShipping']/tbody/tr[5]/td/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3b911d86-c11e-4b8e-96b8-db05c94837b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_chkChargeTaxOnShipping</value>
      <webElementGuid>ef4639f5-2917-4216-9e68-e49b12f6c6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Charge Tax on Shipping</value>
      <webElementGuid>e064a86c-4030-4268-9c7f-f1f3d45d451a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblShipping&quot;)/tbody[1]/tr[5]/td[1]/label[1]</value>
      <webElementGuid>7ed91fb0-7207-48e4-b79c-d69943632518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblShipping']/tbody/tr[5]/td/label</value>
      <webElementGuid>8667c14a-bc33-4ae2-930b-ee8a58554e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consider American Samoa (AS) Orders as Domestic'])[1]/following::label[1]</value>
      <webElementGuid>c83cc478-5c1b-467b-baca-3112f2cf4945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consider Marshall Islands (MH) Orders as Domestic'])[1]/following::label[2]</value>
      <webElementGuid>fad717af-5bb3-4bb6-95cb-ad673b06c9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charge Tax on Gift-Wrap'])[1]/preceding::label[1]</value>
      <webElementGuid>87439cce-220d-41db-842e-6d6cb51d1803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow partial shipment of Order'])[1]/preceding::label[2]</value>
      <webElementGuid>852066c5-157f-4108-8d46-dd02fb7bc23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Charge Tax on Shipping']/parent::*</value>
      <webElementGuid>4ec90f33-15ff-4d59-91e5-5ab881cee174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[2]/td/table/tbody/tr[5]/td/label</value>
      <webElementGuid>4e31fed6-6e05-4879-9a49-b3e263758d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Charge Tax on Shipping' or . = 'Charge Tax on Shipping')]</value>
      <webElementGuid>bc549e3b-b380-4e79-b595-6f261087e4d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
