<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShpDics</name>
   <tag></tag>
   <elementGuidId>e5a4b85e-2e62-402e-a944-b0aef7f34fb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ShippingDiscountField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_ShippingDiscountField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>18edbfda-c28f-4314-a358-ea2d834d0eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ShippingDiscountField</value>
      <webElementGuid>8a0e3d6b-824f-4434-81ad-337f365722cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C$0.00</value>
      <webElementGuid>579dc2bf-9bff-4cdd-a8bd-da566b6dd249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ShippingDiscountField&quot;)</value>
      <webElementGuid>c96153a6-36d7-4c59-922c-e04b2b3adc2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_ShippingDiscountField']</value>
      <webElementGuid>0b7be99b-06f6-42a8-bd5d-77434f05841b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/table/tbody/tr[4]/td[2]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr[5]/td/table/tbody/tr/td[4]/table/tbody/tr[7]/td[2]/span</value>
      <webElementGuid>089dba97-0aa3-4b7d-a1ca-d502c882e4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Discount:'])[1]/following::span[1]</value>
      <webElementGuid>7a632e71-b5cc-47e1-806d-52fe0fade53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$0.00'])[13]/following::span[1]</value>
      <webElementGuid>eff8f878-2a0f-4e24-ae8d-e7c8ec36962f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Handling:'])[1]/preceding::span[1]</value>
      <webElementGuid>23b0026b-9fe9-4ca5-9c36-adf7db4c7147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$0.00'])[15]/preceding::span[1]</value>
      <webElementGuid>a6d4afcb-a74f-418d-981e-a93844e394e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr[7]/td[2]/span</value>
      <webElementGuid>5d43f780-487c-47a6-8f47-a4f4e2776b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_ShippingDiscountField' and (text() = 'C$0.00' or . = 'C$0.00')]</value>
      <webElementGuid>80eb4bdb-c942-477c-a656-e162ab1d2b25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
