<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Check_Name_match_Srchproduct</name>
   <tag></tag>
   <elementGuidId>02ec0203-09a4-4e42-9f89-f5e44d14e28b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_hypSKU</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_hypSKU']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f1032892-6f5c-49e3-a813-d4d5b66428d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_hypSKU</value>
      <webElementGuid>13c5ffee-cacb-4767-aa03-c8edae5af537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../Inventory/Product.aspx?id=Adnan%27s+coffee</value>
      <webElementGuid>69723ee9-2b99-4cb1-842b-d3a65f5d9311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adnan's coffee</value>
      <webElementGuid>8e153193-2830-4e66-af98-52dc22e55be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_hypSKU&quot;)</value>
      <webElementGuid>0fbd55dd-eee3-4f6f-ac4f-bfb1c75e5c4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_hypSKU']</value>
      <webElementGuid>7ca0eef1-ea8b-4d9c-bf17-ebfa69300374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_ProductPicker1_grdMain_ctl00__0']/td[3]/a</value>
      <webElementGuid>be68047e-ea31-4638-a774-1573af533614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPC'])[3]/following::a[4]</value>
      <webElementGuid>5fc327ef-70a6-40e1-ba4e-8d0c8369e2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAP Price'])[1]/following::a[5]</value>
      <webElementGuid>102c472d-fe93-4c6d-94f6-aeba57ef666a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Adnan', &quot;'&quot;, 's coffee')])[2]/preceding::a[1]</value>
      <webElementGuid>c2fc1059-3d03-4f0d-91a2-cfb7e4c745f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khurramcomp'])[2]/preceding::a[1]</value>
      <webElementGuid>8e667e20-a33b-4bd0-8d9e-14ec543fd118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../Inventory/Product.aspx?id=Adnan%27s+coffee')]</value>
      <webElementGuid>543a2bf4-9af3-406c-90ef-b83b4b269330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>069b8c38-6f79-4fde-b100-653fab4753ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_hypSKU' and @href = '../Inventory/Product.aspx?id=Adnan%27s+coffee' and (text() = concat(&quot;Adnan&quot; , &quot;'&quot; , &quot;s coffee&quot;) or . = concat(&quot;Adnan&quot; , &quot;'&quot; , &quot;s coffee&quot;))]</value>
      <webElementGuid>d4412e5e-60e5-4038-b44b-7499b31e02e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
