<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search Items</name>
   <tag></tag>
   <elementGuidId>6b3b248a-5f70-43bb-b2be-f0878f199cd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSearchItems</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSearchItems']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f2e9734-8924-4065-8e05-5b7d810239bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSearchItems</value>
      <webElementGuid>ccb4b6e0-1fb3-4912-8081-f6765dbec946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AddItemstoOrder()</value>
      <webElementGuid>9b837598-8693-4553-a0ef-d6681cf503ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search Items</value>
      <webElementGuid>2476c417-2058-4c55-9c58-8990d6411cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSearchItems&quot;)</value>
      <webElementGuid>622c743f-fa3e-4b6c-bbc2-397ff27b71df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSearchItems']</value>
      <webElementGuid>1b10d30c-1538-4592-a0d8-82cc8513f41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlNewItem']/table/tbody/tr/td[5]/button</value>
      <webElementGuid>d7e8b93f-2a57-4dee-878b-8875ee9628cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/following::button[1]</value>
      <webElementGuid>64443530-7088-4a8e-aaaa-a5cf3a561bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ProductId:'])[1]/following::button[1]</value>
      <webElementGuid>a7e96091-121d-423e-8a4b-5a2c8bef20f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Items'])[1]/preceding::button[1]</value>
      <webElementGuid>6f332f82-936e-49fb-b1b8-ea6706612d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU'])[1]/preceding::button[1]</value>
      <webElementGuid>03046d62-7bf6-4551-80b7-725ebcba848c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search Items']/parent::*</value>
      <webElementGuid>9fb9a577-776e-4621-98ce-b5e4b5869652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c2eb263e-88bf-482d-ab11-cdb6d538ff5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSearchItems' and (text() = 'Search Items' or . = 'Search Items')]</value>
      <webElementGuid>e3dcd90d-cdb9-4112-b34e-013c8649a2a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
