<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search For_ProductPicker1txtSearch</name>
   <tag></tag>
   <elementGuidId>dd49c841-2bcf-4942-81d5-1f13bea6a4f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ProductPicker1_txtSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ProductPicker1_txtSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c61164d8-134a-454f-9f93-0b867c57ec2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ProductPicker1$txtSearch</value>
      <webElementGuid>8d7c85ee-f94b-4dce-954b-9c5582555826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>265d1e0d-da6d-465a-a024-a1a779439f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>du</value>
      <webElementGuid>3f8d8f3c-b678-43f6-aaee-a8b8ddad93a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ProductPicker1_txtSearch</value>
      <webElementGuid>997689bd-2228-458e-a127-a1b70d6819d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ProductPicker1_txtSearch&quot;)</value>
      <webElementGuid>ae035b47-dee1-46c0-9d80-6c4d9f59a38d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ProductPicker1_txtSearch']</value>
      <webElementGuid>caca2059-9bd3-48c2-b82b-c9d4899cf506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_ProductPicker1_pnlSearch']/table/tbody/tr/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>7b932130-f3de-4a6a-91d8-fe119819107f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>c458157f-90da-4323-a90b-5bb791670bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$ProductPicker1$txtSearch' and @type = 'text' and @id = 'ContentPlaceHolder1_ProductPicker1_txtSearch']</value>
      <webElementGuid>611e219c-e755-497a-9d85-546587d6e811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
