<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select_1ProductPicker1btnSearch</name>
   <tag></tag>
   <elementGuidId>263cf041-d0b0-4199-8ddf-5ed257052527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ProductPicker1_btnSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ProductPicker1_btnSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0d8590c-eeca-4bdb-9dda-002af3eac9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>099d0f9c-eb8a-4c4c-a5c0-bb21f752760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ProductPicker1$btnSearch</value>
      <webElementGuid>ea0471f8-e1bd-4828-9fd1-b276b80548a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>330c373b-c365-4184-bc68-ee255a260086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ProductPicker1_btnSearch</value>
      <webElementGuid>7046a835-9642-4d33-859d-f1c34b8e7d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ProductPicker1_btnSearch&quot;)</value>
      <webElementGuid>2de70dc6-f9c7-45bf-8bf0-6bb399a76b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ProductPicker1_btnSearch']</value>
      <webElementGuid>19ff872b-18fa-472b-aec3-0a85f587989c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_ProductPicker1_pnlSearch']/table/tbody/tr/td/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>042caa7c-ca4e-4ecb-9fb7-523a7d71389e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>e7b5f910-cb57-4c07-bf74-818e55149567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder1$ProductPicker1$btnSearch' and @id = 'ContentPlaceHolder1_ProductPicker1_btnSearch']</value>
      <webElementGuid>f2b0edc4-a253-4b31-a74d-2d62603af6d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
