<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UPC_chkSelect_forsrchedproduct</name>
   <tag></tag>
   <elementGuidId>29845867-3de5-49d4-abc7-64b3310eb4aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_chkSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_chkSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bb5b1a7-ead2-41bb-bc28-881f05345b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_chkSelect</value>
      <webElementGuid>5321b05a-6584-447a-9dae-eb1d5ba19c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e945f8f6-87c3-4326-b250-54074c8f1821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ProductPicker1$grdMain$ctl00$ctl04$chkSelect</value>
      <webElementGuid>97d1cf55-fe6d-4702-869f-a21676616fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>calcualateTotalRefund();</value>
      <webElementGuid>dd0cf9d1-de47-4642-aa8a-f0615a400e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_chkSelect&quot;)</value>
      <webElementGuid>d65dacf4-5b1b-4867-aa73-34a9c98900b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_chkSelect']</value>
      <webElementGuid>628585c4-a8ce-4c8a-a24b-ae5e3a416f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_ProductPicker1_grdMain_ctl00__0']/td/input</value>
      <webElementGuid>a7935140-8c3c-41e5-b6a1-9ca6e9f74715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/div/table/tbody/tr/td/input</value>
      <webElementGuid>efe8ee80-38e7-400d-91e6-c5e5dc19ecf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_chkSelect' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$ProductPicker1$grdMain$ctl00$ctl04$chkSelect']</value>
      <webElementGuid>d98cdd0b-6286-404e-96eb-d0b8d60192e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
