<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtQty_Add_Qty</name>
   <tag></tag>
   <elementGuidId>edf7a9d0-0df5-48b1-997e-6a8a16d4fc8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_txtQty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_txtQty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f669823d-c2d9-4cc4-befc-4d8706ead747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ProductPicker1$grdMain$ctl00$ctl04$txtQty</value>
      <webElementGuid>1fe7d5f1-4ac6-4a1a-a465-883991c85627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb2cc7c9-6091-46cd-a79f-6edb69166269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>de18eb96-7ccc-4855-92b8-389c504639f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2763ac3b-2e65-44c1-a22c-a139e59ff888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_txtQty</value>
      <webElementGuid>364a04eb-f375-4bc3-a330-d853a572c1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>calcualateTotalRefund();</value>
      <webElementGuid>21e5f0e1-ada3-47c5-a352-b17424430a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_txtQty&quot;)</value>
      <webElementGuid>2e128679-4b34-4413-9359-57acede43814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_txtQty']</value>
      <webElementGuid>4a1e415c-aa24-4d9c-a930-309cc7eec116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_ProductPicker1_grdMain_ctl00__0']/td[7]/input</value>
      <webElementGuid>8062e616-80e5-482e-ac80-c7fe1517e5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>a35d6ae7-f7d8-49bf-87d0-a6bcd6bf2c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$ProductPicker1$grdMain$ctl00$ctl04$txtQty' and @type = 'text' and @id = 'ContentPlaceHolder1_ProductPicker1_grdMain_ctl00_ctl04_txtQty']</value>
      <webElementGuid>8fd56fcf-e8e3-4d51-8dce-64a2e0769c22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
