<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>For_Paymetns</name>
   <tag></tag>
   <elementGuidId>3082115a-a389-406a-8197-a4c35defcee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ContentPlaceHolder1_OrderStatusPanel1_imgPaymentStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_OrderStatusPanel1_imgPaymentStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a54d496-0965-41c3-9f4d-36911f63dd98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_OrderStatusPanel1_imgPaymentStatus</value>
      <webElementGuid>9c6f67fc-60ee-438d-861c-62feaa5043ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/buttons/admin/RoundButtons/PaymentNone.png</value>
      <webElementGuid>7c1ff0cb-00cf-4caa-b813-e86733f20b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_OrderStatusPanel1_imgPaymentStatus&quot;)</value>
      <webElementGuid>ae4147d4-fae4-4459-a642-7b4b9639e024</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ContentPlaceHolder1_OrderStatusPanel1_imgPaymentStatus']</value>
      <webElementGuid>9a620ad3-afd3-4fce-a366-b4f58f26a13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ContentPlaceHolder1_OrderStatusPanel1_hypReceivePayment']/img</value>
      <webElementGuid>37d20e2a-15ef-4986-a778-c72e48660225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/a/img</value>
      <webElementGuid>202679f7-a60b-464c-82b3-6288d39bc83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'ContentPlaceHolder1_OrderStatusPanel1_imgPaymentStatus' and @src = '/images/buttons/admin/RoundButtons/PaymentNone.png']</value>
      <webElementGuid>198a06a1-8bf7-44f0-9a63-5b864451b55e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
