<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Get_span_Charged</name>
   <tag></tag>
   <elementGuidId>0f3fc614-fbfc-49b2-9dbd-6f39a3546df0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_OrderStatusPanel1_lblPaymentStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_OrderStatusPanel1_lblPaymentStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a00d07a3-d92d-470d-9de0-cfc675306424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_OrderStatusPanel1_lblPaymentStatus</value>
      <webElementGuid>cd288aaf-c6a7-4ea5-aab6-f89eed02015d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Charged</value>
      <webElementGuid>7e664865-124c-430f-ae83-d250d2503c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_OrderStatusPanel1_lblPaymentStatus&quot;)</value>
      <webElementGuid>dc103355-0959-42e1-9e17-35f9cad49864</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_OrderStatusPanel1_lblPaymentStatus']</value>
      <webElementGuid>59f8b585-bfc7-46ad-9f30-f2810669bf59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_OrderStatusPanel1_trPaymentStatus']/td[2]/span</value>
      <webElementGuid>9e4a6bfb-b4b9-4216-a415-230431df573b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='InProcess'])[1]/following::span[1]</value>
      <webElementGuid>e995898f-38c4-4561-83e7-7eddc7de7998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Store Order'])[1]/following::span[2]</value>
      <webElementGuid>a54cabfd-4cb6-4131-8e1b-ee4384809ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Not Confirmed'])[1]/preceding::span[1]</value>
      <webElementGuid>67da6bde-bbb3-4146-a60b-0e13468d626f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Not Confirmed'])[1]/preceding::span[2]</value>
      <webElementGuid>29ac6060-595f-4a8d-9c64-77a8710aefb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Charged']/parent::*</value>
      <webElementGuid>db72ce9b-50b1-4412-89ef-6e97900a450d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/span</value>
      <webElementGuid>1a4131bc-2248-498f-b065-aaf1efa2a4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_OrderStatusPanel1_lblPaymentStatus' and (text() = 'Charged' or . = 'Charged')]</value>
      <webElementGuid>e2dddc56-e6a6-4b9d-aa90-18168e6d37e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
