<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_imgShippingStatus</name>
   <tag></tag>
   <elementGuidId>c06b3b51-a278-4177-b1b8-a7a7347775b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ContentPlaceHolder1_OrderStatusPanel1_imgShippingStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_OrderStatusPanel1_imgShippingStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7eb15d33-dc22-418a-b5f7-ba2c1a4b8ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_OrderStatusPanel1_imgShippingStatus</value>
      <webElementGuid>3d469151-963c-4d60-8105-d91364a77b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/buttons/admin/RoundButtons/ShippingUnshipped.png</value>
      <webElementGuid>6c34ba9a-61a0-4a58-9c16-cf6b4aef337a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_OrderStatusPanel1_imgShippingStatus&quot;)</value>
      <webElementGuid>748bd473-9b53-4ad9-b1bd-ae37323ad373</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ContentPlaceHolder1_OrderStatusPanel1_imgShippingStatus']</value>
      <webElementGuid>d1f70b94-d8b3-4d32-aa61-635171b25694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ContentPlaceHolder1_OrderStatusPanel1_hypShipOrder']/img</value>
      <webElementGuid>f0ac882e-aef8-49a1-a573-49b666a64ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td/a/img</value>
      <webElementGuid>dae64130-9bf5-450f-888b-fd82fecd93c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'ContentPlaceHolder1_OrderStatusPanel1_imgShippingStatus' and @src = '/images/buttons/admin/RoundButtons/ShippingUnshipped.png']</value>
      <webElementGuid>405b6eec-9b13-4d15-8ace-b0ae48b83414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
