<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_QtyReturned</name>
   <tag></tag>
   <elementGuidId>8be86211-528f-4274-890f-093c920a7c10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyReturned']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyReturned</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a83eff3-28b4-4c5b-8cb7-cd89be2edc4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdItems$ctl00$ctl04$txtQtyReturned</value>
      <webElementGuid>7c143e22-3c24-4619-90c4-7dd8e7024366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26bea70d-f091-40bf-b537-2121086fb82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fc98e6cb-1a3f-4521-99fd-941050d1eebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyReturned</value>
      <webElementGuid>8bc4e025-3b92-4b42-9550-a20bae7e4df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyReturned&quot;)</value>
      <webElementGuid>4bb2475d-ab1d-438c-910f-f764d2ebd203</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyReturned']</value>
      <webElementGuid>afbcfad0-adcc-4f4f-84cf-febe9fb6f8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdItems_ctl00__0']/td[7]/input</value>
      <webElementGuid>e9a0df94-20b6-4912-8080-bf85b97a3650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>f5b7861f-0e9d-40ca-9435-0bdee6f2eecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$grdItems$ctl00$ctl04$txtQtyReturned' and @type = 'text' and @id = 'ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyReturned']</value>
      <webElementGuid>80d533ab-eb97-41c7-82ce-33af9125ee93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
