<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_chkSelect</name>
   <tag></tag>
   <elementGuidId>bfa440eb-4f79-4b39-b4f5-0403933dbd7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdItems_ctl00_ctl04_chkSelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdItems_ctl00_ctl04_chkSelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5400890-a221-4753-b620-ac9eafdcc7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdItems_ctl00_ctl04_chkSelect</value>
      <webElementGuid>28fba2fb-28bc-4197-a5bf-ac70b3c3f914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>123cb022-b320-4faa-8535-1b1a78349dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdItems$ctl00$ctl04$chkSelect</value>
      <webElementGuid>139a96ba-20a0-4532-ac8c-889557e92339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdItems_ctl00_ctl04_chkSelect&quot;)</value>
      <webElementGuid>6bd8476d-f441-4a86-adef-beb6b068a64c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdItems_ctl00_ctl04_chkSelect']</value>
      <webElementGuid>5a3d58c0-c0b4-4a57-8710-3fd84641149f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdItems_ctl00__0']/td[2]/input</value>
      <webElementGuid>a3a3cdee-704c-4d36-99d1-44df922a43b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>31a030c8-2cf7-44ea-abd8-85ebd5c44f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_grdItems_ctl00_ctl04_chkSelect' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$grdItems$ctl00$ctl04$chkSelect']</value>
      <webElementGuid>a389f0b3-3a83-4b62-97f7-8bb22deccebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
