<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnSubmitPayment</name>
   <tag></tag>
   <elementGuidId>0671d8c4-58d4-425c-81f2-b74d3c063fcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_btnSubmit2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_btnSubmit2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70c796ba-6de0-4595-8aa9-32610da78ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>3590457e-7578-4378-bb0b-c73e84e3c6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$btnSubmit2</value>
      <webElementGuid>e9449576-e8f1-4dd7-b976-e9fd4abac28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_btnSubmit2</value>
      <webElementGuid>653f3c6d-8560-42ac-8dac-6aa74177637b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/app/Submit.jpg</value>
      <webElementGuid>ed795c00-3974-45dc-a438-47e0a93a8ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.style.display='none';</value>
      <webElementGuid>70b5641d-78fb-464c-8de7-2f15baa95173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_btnSubmit2&quot;)</value>
      <webElementGuid>45068a73-461b-48d5-aa59-49d6bcf95d22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_btnSubmit2']</value>
      <webElementGuid>d7bc4aea-fd42-413c-b103-d04cf4c0ba5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/table/tbody/tr[4]/td[2]/table/tbody/tr[2]/td/table/tbody/tr[2]/td/table/tbody/tr[5]/td/table[2]/tbody/tr[2]/td/input</value>
      <webElementGuid>039f8087-32aa-4f9f-99fc-1b0ddf40286e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[2]/td/input</value>
      <webElementGuid>f061e5ed-00bd-4db8-a857-0c160acf5238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$btnSubmit2' and @id = 'ContentPlaceHolder1_btnSubmit2' and @src = '../images/app/Submit.jpg']</value>
      <webElementGuid>13ad0984-811d-4d1f-a425-8b89d3845473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
