<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnCreateReturnImg</name>
   <tag></tag>
   <elementGuidId>6afec9ee-a53c-4509-ac7e-96ff465613fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_btnCreateReturnImg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_btnCreateReturnImg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0b1f572-a04b-4473-9b3c-5985f3f7796d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>67e1731e-e2da-41dc-8753-82435e58fcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$btnCreateReturnImg</value>
      <webElementGuid>bbfb0b3e-dbfb-4a45-8521-e63dfadb6a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_btnCreateReturnImg</value>
      <webElementGuid>68296305-60b8-44a3-a623-5786827a3b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/app/Button-Continue.jpg</value>
      <webElementGuid>1444f8d8-1bec-48bf-8882-d09272690660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>onSubmit(this);</value>
      <webElementGuid>a1c0931d-d8fa-4631-b02e-f48335fcfc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_btnCreateReturnImg&quot;)</value>
      <webElementGuid>07d83ae6-1620-4731-b434-1d328e494259</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_btnCreateReturnImg']</value>
      <webElementGuid>7d34a236-d391-4b4a-8dc7-448651419c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlNewReturn']/table/tbody/tr[5]/td/input</value>
      <webElementGuid>7f445d0e-3abf-4235-84d4-dd4eee25482b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/input</value>
      <webElementGuid>42b0745f-886d-4429-8c08-3f7ad1d62580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$btnCreateReturnImg' and @id = 'ContentPlaceHolder1_btnCreateReturnImg' and @src = '/images/app/Button-Continue.jpg']</value>
      <webElementGuid>8411a690-3d4e-4d61-aca6-b4007128e705</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
