<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Orders</name>
   <tag></tag>
   <elementGuidId>face59a5-2b4c-4411-9628-602a3382b95b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mnuMainOrders']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mnuMainOrders</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>664c0d6b-99cb-473b-8a81-d68b78eb5df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rmLink rmRootLink rmFocused</value>
      <webElementGuid>769da1a1-892d-4a0f-86f3-36eed6876c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mnuMainOrders</value>
      <webElementGuid>705966c5-2b10-44a1-aad9-65ae99248d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Orders/ManageOrders.aspx?filters=cleared</value>
      <webElementGuid>83aa5207-de03-4225-832c-d9a274d89ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orders</value>
      <webElementGuid>e117bbad-08c7-40bd-a8a8-428082dca980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mnuMainOrders&quot;)</value>
      <webElementGuid>321c5af5-031d-4356-8ad6-b2e50a5c598a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mnuMainOrders']</value>
      <webElementGuid>6b97a1a9-4e1a-4813-8720-e4f8b234ba6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mnyMain']/ul/li[4]/a</value>
      <webElementGuid>dd51bebd-94ac-47dd-a51f-f0ae57c27f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channel Customers'])[1]/following::a[1]</value>
      <webElementGuid>07f746c6-71c7-4797-bada-a5472373470f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Customers'])[1]/following::a[2]</value>
      <webElementGuid>c3b89417-18bc-4173-9ca3-d4241cc2d181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Orders'])[1]/preceding::a[1]</value>
      <webElementGuid>7afb9569-8d5e-44e9-b10f-3e9b9a54517e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Orders/ManageOrders.aspx?filters=cleared')]</value>
      <webElementGuid>40d4313c-a8dc-47b4-aef5-a3071289b9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>ad7d6961-c38b-4b47-a3f8-bafd56fcc027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'mnuMainOrders' and @href = 'Orders/ManageOrders.aspx?filters=cleared' and (text() = 'Orders' or . = 'Orders')]</value>
      <webElementGuid>b74a86e2-8bbb-498b-8ae8-0751a436be8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
