<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SelectCheckBox</name>
   <tag></tag>
   <elementGuidId>1a3fde09-4beb-4d4d-9118-ab4dcd39a7e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>276ee72c-48cf-4b8d-b44c-6c096da5067f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox</value>
      <webElementGuid>3077d248-f80f-415e-9db3-176d856a2187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4690e725-30a8-4140-a1de-8d5b2db1ff73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl04$columnSelectCheckBox</value>
      <webElementGuid>3a6a5e08-71c5-4973-b07f-a11ba04a7acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox&quot;)</value>
      <webElementGuid>8810761d-8b3b-4aee-9c26-0a75d82a1f41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox']</value>
      <webElementGuid>ad3ab0eb-707c-4bb6-935a-236e7aedc483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdMain_ctl00__0']/td[3]/input</value>
      <webElementGuid>c540acf2-7807-462c-b967-a0da71939c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div/table/tbody/tr/td[3]/input</value>
      <webElementGuid>4419112d-f17b-4905-8945-8a656321809a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl04$columnSelectCheckBox']</value>
      <webElementGuid>29d7c916-fb31-457c-a4a2-57116ab19102</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
