<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>541713e6-94be-4a31-9e9d-f49af96ab0a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEdit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ContentPlaceHolder1_ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEdit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>682ac4af-cd8c-434c-8fa1-8f50a6127721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEdit</value>
      <webElementGuid>708184ca-3581-4aeb-988b-e606a7f1cd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Merchant_Taxes_edit.aspx?MerchantID=164&amp;TaxID=55</value>
      <webElementGuid>7e7b18e1-dc69-425a-8f2b-ff9db03c1140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>e2c46214-1989-4710-91fe-5fdd2356f56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEdit&quot;)</value>
      <webElementGuid>b2bb8462-6d2e-4c59-9b8c-749de9802d02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ContentPlaceHolder1_ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEdit']</value>
      <webElementGuid>cf01d967-6655-4366-988b-241ec028f85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_ContentPlaceHolder1_grdMain_ctl00__0']/td[2]/a</value>
      <webElementGuid>f996547b-8c7f-494e-8d3c-450923cdbbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>3338f3cb-a82b-45db-aeb3-ecc0256075ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[2]/following::a[1]</value>
      <webElementGuid>e121db13-5f4a-4db1-863a-e900c06ff9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/preceding::a[1]</value>
      <webElementGuid>963199c1-e981-458b-a041-5959a5eeff8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dummy'])[1]/preceding::a[1]</value>
      <webElementGuid>593152d4-1adb-4824-b1ca-e98577205f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>fbdb8ac3-8531-40bb-a758-e0ff92d30ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Merchant_Taxes_edit.aspx?MerchantID=164&amp;TaxID=55')]</value>
      <webElementGuid>94905bc9-701a-487c-ae77-ad1691f0757d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table/tbody/tr/td[2]/a</value>
      <webElementGuid>ae7ab6bf-78e3-42b6-a8ba-2a6d6f413a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ContentPlaceHolder1_ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEdit' and @href = 'Merchant_Taxes_edit.aspx?MerchantID=164&amp;TaxID=55' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>934d3d09-5cb6-4482-aced-6aa7ebbc2071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
