<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckorUncheckState</name>
   <tag></tag>
   <elementGuidId>ce231f6a-986f-4230-bc75-7ef4a0be0bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ContentPlaceHolder1_chkDoNotChargeTaxOnShipping</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ContentPlaceHolder1_chkDoNotChargeTaxOnShipping']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>260efd28-b0e4-4ca2-b582-0de3a1cb71a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ContentPlaceHolder1_chkDoNotChargeTaxOnShipping</value>
      <webElementGuid>13ca21cc-14fd-4bfa-84cf-c53af085bf74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8a6631d3-0f31-4a70-8466-2d510a4b221b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ContentPlaceHolder1$ContentPlaceHolder1$chkDoNotChargeTaxOnShipping</value>
      <webElementGuid>93ac307b-c215-4256-8eaf-10c7587895cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ContentPlaceHolder1_chkDoNotChargeTaxOnShipping&quot;)</value>
      <webElementGuid>d96fc100-d107-473e-9cec-1ec843280ad0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ContentPlaceHolder1_chkDoNotChargeTaxOnShipping']</value>
      <webElementGuid>4b435efe-a86a-486b-a96f-7a6376772c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_ContentPlaceHolder1_pnlTaxDetails']/table/tbody/tr[6]/td/input</value>
      <webElementGuid>2e2e00d8-b373-4247-b97b-f378cc32828e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>bd7db5d4-3203-4338-914f-cc783ceaf138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_ContentPlaceHolder1_chkDoNotChargeTaxOnShipping' and @type = 'checkbox' and @name = 'ctl00$ctl00$ContentPlaceHolder1$ContentPlaceHolder1$chkDoNotChargeTaxOnShipping']</value>
      <webElementGuid>026d5982-f956-46b8-967e-dda091b0f0e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
