<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>8883df00-1e12-4208-8757-d20abf26ae78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEditAppSetting']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEditAppSetting</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1aa447c9-df77-4f8e-a23f-fe094645d68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEditAppSetting</value>
      <webElementGuid>44d5dda9-5899-4f3c-9b31-f4702f4a910e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/AppSetting_Edit.aspx?SettingName=EnableAlternateTaxCalculation&amp;ignorepassword=true</value>
      <webElementGuid>5206b259-fa25-48ab-8faf-cd46d18f2817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>590c2ec4-c03c-4e08-81d5-081983472e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEditAppSetting&quot;)</value>
      <webElementGuid>084c4c12-9e0a-4bfe-be6b-ebe79f69c68c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEditAppSetting']</value>
      <webElementGuid>c4808813-23a2-40ff-a54a-6043c1a4f473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdMain_ctl00__0']/td/a</value>
      <webElementGuid>ae1c8ea3-1a2b-4208-aae9-4a705619daa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Edit')])[3]</value>
      <webElementGuid>3b27d505-ebe6-4ff1-ad4a-1d641b5f4687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::a[1]</value>
      <webElementGuid>4e5b3810-93a8-46fc-beff-b2f2cd752475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/preceding::a[1]</value>
      <webElementGuid>3dc917e3-bba6-4b6c-b0c9-5506a3e50e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EnableAlternateTaxCalculation'])[1]/preceding::a[2]</value>
      <webElementGuid>0fed218f-76a9-4814-8ffc-235791c914cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>dec8ee5c-c3c3-4e8e-b265-b71ecccb2a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/AppSetting_Edit.aspx?SettingName=EnableAlternateTaxCalculation&amp;ignorepassword=true')]</value>
      <webElementGuid>a218441a-14ef-4e79-a175-3e1c387ffd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/table/tbody/tr/td/a</value>
      <webElementGuid>cf8ba0ec-c29d-40fb-bb09-0403bd501ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ContentPlaceHolder1_grdMain_ctl00_ctl04_hypEditAppSetting' and @href = '/admin/AppSetting_Edit.aspx?SettingName=EnableAlternateTaxCalculation&amp;ignorepassword=true' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>efbccd5b-1fd6-4009-ab43-b33dcfaee9d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
