<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SelectCheckBox</name>
   <tag></tag>
   <elementGuidId>d20c8ae9-9f1d-4089-9144-fdbe366c1d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9770629-c421-4e51-89db-e3ed144704df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox</value>
      <webElementGuid>65f40b99-9f02-4ac1-9593-ead8b282892d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>12182d63-b094-4888-a545-d25ccb377119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl04$columnSelectCheckBox</value>
      <webElementGuid>3b770dba-c02f-46d7-a9d6-f20c0dbaf0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox&quot;)</value>
      <webElementGuid>1a61e84b-cb83-465c-95a7-f550d9c66edd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox']</value>
      <webElementGuid>58c88b17-72b6-44bd-9204-2d26b3647d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdMain_ctl00__0']/td/input</value>
      <webElementGuid>9b0df1b3-b246-40f0-b43e-2e9f630d2e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>e49c49f2-d64a-4694-a0a4-9d075e5b675a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_grdMain_ctl00_ctl04_columnSelectCheckBox' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl04$columnSelectCheckBox']</value>
      <webElementGuid>afa5fb7b-9b0b-4f99-a1d6-09a6d8e2bf16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
