<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Home_Present</name>
   <tag></tag>
   <elementGuidId>621f1aaa-8727-406b-960d-77555efa79df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SiteMapPath1 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='SiteMapPath1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>58680b8d-4e5c-4cd7-a128-3225b68726e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>84493aeb-186c-48e5-b780-6c5d2e959680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteMapPath1&quot;)/span[1]</value>
      <webElementGuid>478d90be-b60d-415d-ae84-321f266d7778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='SiteMapPath1']/span</value>
      <webElementGuid>71f18884-585a-4722-819d-9361152cbc36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip Navigation Links'])[1]/following::span[1]</value>
      <webElementGuid>23dc2bf6-4426-4306-b9e4-7ca5c1eadfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show All'])[1]/following::span[2]</value>
      <webElementGuid>b10963bc-e38b-458b-94f0-c549b39fed99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Counts'])[1]/preceding::span[1]</value>
      <webElementGuid>a7e8aff4-4fd6-42af-ba9a-5c988eca83d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>10154a75-ed22-4f2f-9b3a-88d2eb709fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>c646ca7f-cda8-40da-b70a-c328479c4bc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
