<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalDiscount</name>
   <tag></tag>
   <elementGuidId>474c6213-21d4-457b-8a1c-6638161835a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_DiscountField']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_DiscountField</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d33d7bfa-5a2e-4871-aa71-5d412f48ed31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_DiscountField</value>
      <webElementGuid>76e562d0-8414-4ffe-bc9a-0e11d2973989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C$0.00</value>
      <webElementGuid>02bb123e-48fb-473b-8a0c-f797a4eddce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_DiscountField&quot;)</value>
      <webElementGuid>4333727b-368e-4826-8ce8-a2a38f12bb1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_DiscountField']</value>
      <webElementGuid>51282e72-0aa1-4ffc-9678-15fe8a97a591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/table/tbody/tr[4]/td[2]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr[5]/td/table/tbody/tr/td[4]/table/tbody/tr[3]/td[2]/span</value>
      <webElementGuid>2d2856ad-fbe6-4656-8e47-28d41841aa8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Discount:'])[1]/following::span[1]</value>
      <webElementGuid>9c995562-f7a4-4838-8c09-e61dcd536b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$0.00'])[12]/following::span[1]</value>
      <webElementGuid>f1b46c72-61a6-4234-bd9e-c6db67426ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax:'])[2]/preceding::span[1]</value>
      <webElementGuid>b074898a-e326-43da-a4cb-3304ebb6a245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$0.00'])[14]/preceding::span[2]</value>
      <webElementGuid>17092162-7eb2-44b7-a187-fa2f79de0bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr[3]/td[2]/span</value>
      <webElementGuid>3542bc10-c06a-4bf6-882b-e207e493ea40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_DiscountField' and (text() = 'C$0.00' or . = 'C$0.00')]</value>
      <webElementGuid>1b1ea76a-738d-44d8-b7fa-9696ccde19c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
