<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ShowHide textbox to paste SKU list</name>
   <tag></tag>
   <elementGuidId>ea0add03-cc17-420a-b030-912be95310a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ContentPlaceHolder1_ProductPicker1_hypshowHidePasteSKUList']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ProductPicker1_hypshowHidePasteSKUList</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7f3a147-6f19-42b1-bc25-08e74cb0f682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ProductPicker1_hypshowHidePasteSKUList</value>
      <webElementGuid>641ba66d-10db-402a-8a16-334d00d1c876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:togglePasteSKUList();</value>
      <webElementGuid>41dbfed9-a885-4763-91ce-a459fbfa073b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show/Hide textbox to paste SKU list</value>
      <webElementGuid>40c37090-b3f8-440e-a47c-86997f4e15ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ProductPicker1_hypshowHidePasteSKUList&quot;)</value>
      <webElementGuid>271ef5bc-288a-4aeb-b4d5-f09680a14105</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ContentPlaceHolder1_ProductPicker1_hypshowHidePasteSKUList']</value>
      <webElementGuid>3c287f95-2c71-4490-bae1-1c6597796df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/table/tbody/tr[5]/td/table/tbody/tr[2]/td/a</value>
      <webElementGuid>2551df99-ba9f-4f56-85bf-df0ec02d2714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Show/Hide textbox to paste SKU list')]</value>
      <webElementGuid>6ee6a1c6-1c2b-420f-afce-44c53b28046c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exclude Matrix parent'])[1]/following::a[1]</value>
      <webElementGuid>4b05e755-9546-4d32-a461-5e999b692686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exclude Inactive Products'])[1]/following::a[1]</value>
      <webElementGuid>ae0f9471-b22a-47fe-87ff-727af663932c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show/Hide textbox to paste SKU list']/parent::*</value>
      <webElementGuid>b006419b-cc9b-4cdd-b3b5-25c0943c0d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:togglePasteSKUList();')]</value>
      <webElementGuid>1c2af897-42d0-4f87-8488-e9b6c21ca403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/a</value>
      <webElementGuid>7961520e-797f-407e-b513-6539cb896659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ContentPlaceHolder1_ProductPicker1_hypshowHidePasteSKUList' and @href = 'javascript:togglePasteSKUList();' and (text() = 'Show/Hide textbox to paste SKU list' or . = 'Show/Hide textbox to paste SKU list')]</value>
      <webElementGuid>509cd8cb-c237-4d2f-b4e5-2fcadd6fb90a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
