<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_SearchSKUs_Click</name>
   <tag></tag>
   <elementGuidId>8cb6b544-6880-4452-8d27-0607d4ad71eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ProductPicker1_btnShowPastedSKUs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ProductPicker1_btnShowPastedSKUs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8d0f333-9982-42de-a2ac-ddbc96e5444a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ee9df434-0bc5-4168-a67a-7f04ffdd3eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ProductPicker1$btnShowPastedSKUs</value>
      <webElementGuid>fdbf75a8-a881-472c-a274-4a88441e72ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search SKUs</value>
      <webElementGuid>17946dd7-1c05-4326-bf0b-84f7510debef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ProductPicker1_btnShowPastedSKUs</value>
      <webElementGuid>cd525f95-bfe6-4b7c-9d8d-b21e59c663fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ProductPicker1_btnShowPastedSKUs&quot;)</value>
      <webElementGuid>bf975dac-9138-44b9-a269-523f7a4aa2ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ProductPicker1_btnShowPastedSKUs']</value>
      <webElementGuid>9cc69f5d-3d4c-41b9-a510-3f49ae7093c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divPasteSKUList']/table/tbody/tr[4]/td/input</value>
      <webElementGuid>7ce50e6a-5f52-4aa8-9ba0-f754f76dbeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>6a862d30-5b36-4a34-8ede-40ffc0c08f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ContentPlaceHolder1$ProductPicker1$btnShowPastedSKUs' and @id = 'ContentPlaceHolder1_ProductPicker1_btnShowPastedSKUs']</value>
      <webElementGuid>57e1e6cf-d488-42fe-86dc-ad6f0ebabad3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
