<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_ProductPriceinOrder</name>
   <tag></tag>
   <elementGuidId>73c60a55-ef4e-48d8-9973-0412c4e12400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39d93b12-208c-4809-8328-c655c8e961ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl04$txtPrice</value>
      <webElementGuid>f8ec67b1-0da2-4413-8f63-be121b945fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11553ce3-6aa2-498c-9b21-a41f5ddcf452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>170b9f2f-3134-40d5-9be8-49a9eb05b7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice</value>
      <webElementGuid>15924b99-d886-488c-aa34-4c232b869359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>adjustSubtotal('ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice', 'ContentPlaceHolder1_grdMain_ctl00_ctl04_txtQty', 'ContentPlaceHolder1_grdMain_ctl00_ctl04_lblSubTotal');</value>
      <webElementGuid>b7a03cff-7df4-404f-af12-74c0caf1f55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice&quot;)</value>
      <webElementGuid>74293e2b-cddc-405e-8bd3-01d3b7ee0fc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice']</value>
      <webElementGuid>0ae064a7-0c64-45ac-beca-436034a6426d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdMain_ctl00__0']/td[5]/input</value>
      <webElementGuid>4d960cf7-2ff9-4612-835c-ea864c38cfe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/table/tbody/tr/td[5]/input</value>
      <webElementGuid>e69bd71c-3f7e-496b-947e-27ebe9e77b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl04$txtPrice' and @type = 'text' and @id = 'ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice']</value>
      <webElementGuid>bb4afdfd-67fe-4833-a3c8-cab29b663c0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
