<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputCardHolderName</name>
   <tag></tag>
   <elementGuidId>dd91d7a8-64fa-49b3-b31e-d4dfe5a40cab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_txtCardNameOnCard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_txtCardNameOnCard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0331151d-f38f-41b8-9669-f7a4faeb8b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$txtCardNameOnCard</value>
      <webElementGuid>4dd05417-1112-45ab-bc40-07ff55f43c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87366085-4663-47c5-88a1-f27d3972e0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_txtCardNameOnCard</value>
      <webElementGuid>0d92cc63-fd07-4168-91d5-45fb74d1d6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_txtCardNameOnCard&quot;)</value>
      <webElementGuid>dd43d72a-9e46-4428-82e9-3b717195844d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_txtCardNameOnCard']</value>
      <webElementGuid>3f5248e4-9e61-4ee2-bc59-ca43a01e6c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trPaymentCC']/td/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>03b6b104-5fe4-43f5-b9a4-8f09afcef9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>c4e9314b-75af-4cdf-9170-eb0df2d3e9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$txtCardNameOnCard' and @type = 'text' and @id = 'ContentPlaceHolder1_txtCardNameOnCard']</value>
      <webElementGuid>18ddff59-345e-43b6-af7c-c3b70ecd3f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
