<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_expiresDateYr</name>
   <tag></tag>
   <elementGuidId>2a8c5cac-7c45-4f2d-8377-819edc7ca01a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ContentPlaceHolder1_ddlExpiryYear']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ddlExpiryYear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2010c923-eef4-4534-8cdb-aeaee394c8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ddlExpiryYear</value>
      <webElementGuid>82c0e2ec-e1f0-4afb-8d8a-d73898d780c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ddlExpiryYear</value>
      <webElementGuid>dfffbe94-3cb4-454c-8483-0d66f7bef8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			2023
			2024
			2025
			2026
			2027
			2028
			2029
			2030
			2031
			2032
			2033

		</value>
      <webElementGuid>f95289b9-37ea-4faa-adef-b4caa9dd2e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ddlExpiryYear&quot;)</value>
      <webElementGuid>ec01e6dc-c22b-440d-ae45-cad558818b0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ContentPlaceHolder1_ddlExpiryYear']</value>
      <webElementGuid>dbe9ef70-11a9-48d9-84af-4f0881626e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trPaymentCC']/td/table/tbody/tr[4]/td[2]/select[2]</value>
      <webElementGuid>0c265e10-e185-41c7-9913-42592d32a953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expires:'])[1]/following::select[2]</value>
      <webElementGuid>5aa04045-427d-4353-a921-37efeb991eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number:'])[1]/following::select[2]</value>
      <webElementGuid>5ebdafab-e014-4314-80be-78d21ad00224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name:'])[1]/preceding::select[1]</value>
      <webElementGuid>0f8f5df1-e3ab-4316-97f6-310599f96e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy From Billing'])[1]/preceding::select[1]</value>
      <webElementGuid>d1a863fc-78ee-48ae-913d-fadfbdc38ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>1bcf1d76-6d4e-4f0b-b13f-649326d8e9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder1$ddlExpiryYear' and @id = 'ContentPlaceHolder1_ddlExpiryYear' and (text() = '
			2023
			2024
			2025
			2026
			2027
			2028
			2029
			2030
			2031
			2032
			2033

		' or . = '
			2023
			2024
			2025
			2026
			2027
			2028
			2029
			2030
			2031
			2032
			2033

		')]</value>
      <webElementGuid>1b2849fd-70b4-4be9-8e58-c536be83fa0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
