<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add 2 disc</name>
   <tag></tag>
   <elementGuidId>db85c8dd-573a-4baf-859d-969ff341d0ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl06_txtdiscountValue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdMain_ctl00_ctl06_txtdiscountValue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98003949-d305-4e67-b921-a45e96709592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl06$txtdiscountValue</value>
      <webElementGuid>79ac3e99-ca37-4fe8-98bd-196de910753e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7e33784-6355-4fcf-bf3d-0c7b60627602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b50d6ed3-d5ab-479b-b14a-d5a6e1533992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdMain_ctl00_ctl06_txtdiscountValue</value>
      <webElementGuid>d338a893-b3d4-48d7-a2bd-d2915a43afcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdMain_ctl00_ctl06_txtdiscountValue&quot;)</value>
      <webElementGuid>21901861-834d-4c9e-a1cc-16e87b8f23cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl06_txtdiscountValue']</value>
      <webElementGuid>4cd1c5b2-7636-4d47-9d19-674cf756911c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdMain_ctl00__1']/td[8]/input</value>
      <webElementGuid>7eb146b7-c4ac-479b-a362-64f3777367d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/input</value>
      <webElementGuid>2cf22afe-8b96-491f-8c6c-664d7363800f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl06$txtdiscountValue' and @type = 'text' and @id = 'ContentPlaceHolder1_grdMain_ctl00_ctl06_txtdiscountValue']</value>
      <webElementGuid>5014d5ac-fa2a-451e-ab1a-74e7277a3e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
