<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FullyShipped</name>
   <tag></tag>
   <elementGuidId>f80ec30c-fe86-423b-83cb-72b6caa9ea70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_OrderStatusPanel1_lblShippingStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_OrderStatusPanel1_lblShippingStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31a48bbb-f13e-4b5d-af76-801612cb57af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_OrderStatusPanel1_lblShippingStatus</value>
      <webElementGuid>bdc22c96-2ecd-44f1-986c-0392a0509d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fully Shipped</value>
      <webElementGuid>9610bd89-a38f-419c-a8da-e91a675fa50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_OrderStatusPanel1_lblShippingStatus&quot;)</value>
      <webElementGuid>67e75979-5e1c-4c36-a367-958b139ba90f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_OrderStatusPanel1_lblShippingStatus']</value>
      <webElementGuid>ace7ac7c-2392-43f5-be0a-01ffabb14518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_OrderStatusPanel1_trShippingstatus']/td[2]/span</value>
      <webElementGuid>37fb5326-3936-4f8a-a5c9-16517c44052a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Picked'])[1]/following::span[1]</value>
      <webElementGuid>036d4d5b-7313-436c-9ef0-61a526e823d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOT Rush Order'])[1]/following::span[2]</value>
      <webElementGuid>42d0cc85-1167-44ae-b3e2-478ba3bdc13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipped Not Verified'])[1]/preceding::span[1]</value>
      <webElementGuid>bd58f145-d3d5-4498-9581-aba48c603cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropship: None'])[1]/preceding::span[2]</value>
      <webElementGuid>a60e2035-fd43-4593-b1b6-5ad19697d311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fully Shipped']/parent::*</value>
      <webElementGuid>3b48fecc-30b4-4a58-913b-f5dbccae4879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/span</value>
      <webElementGuid>640a2657-f419-43b2-bc2e-b2e7bccb554b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_OrderStatusPanel1_lblShippingStatus' and (text() = 'Fully Shipped' or . = 'Fully Shipped')]</value>
      <webElementGuid>b44d7acf-58f1-4d15-9687-c9e65a92d217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
