<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveMainBtn</name>
   <tag></tag>
   <elementGuidId>907f0821-34f2-42f6-81ef-0960c3dffdc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_btnSave']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_btnSave</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51063232-eacb-493f-9bde-b3c61ba8e87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>5526f397-8886-486a-ae29-50ec2f92a956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$btnSave</value>
      <webElementGuid>d840fabc-ef9e-49ca-ab8e-249ddc0f48b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_btnSave</value>
      <webElementGuid>9e1e7816-667e-4fd5-8f9e-a468f3219612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/app/SaveOrder.jpg</value>
      <webElementGuid>5eef98b9-50bb-4c51-bf1d-8efee2dd09c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hideMe(this);</value>
      <webElementGuid>48abf293-d506-4489-8619-cd90feea9183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_btnSave&quot;)</value>
      <webElementGuid>a4ab4a7a-52ee-4e57-aa30-78aa56ebd6ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_btnSave']</value>
      <webElementGuid>897effe3-9b44-4142-bc1e-8db3db1c42b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_trMainRow']/td/table/tbody/tr[6]/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>f1e1fb6d-e33f-4251-9d55-673a978eaaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>ba94c1c3-666c-47c3-864e-43ed63589976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$btnSave' and @id = 'ContentPlaceHolder1_btnSave' and @src = '../images/app/SaveOrder.jpg']</value>
      <webElementGuid>b319cc06-11a9-4839-b464-e154a60cac96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
