<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select order</name>
   <tag></tag>
   <elementGuidId>18b39293-0a4e-458c-abba-9598e8a77fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_hypOrderId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdMain_ctl00_ctl04_hypOrderId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>84412cfe-aacb-4b75-8cd0-c98fdddfa4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdMain_ctl00_ctl04_hypOrderId</value>
      <webElementGuid>22396f2a-6ca0-4112-8d39-b46b815a3ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>selectWhole(this);</value>
      <webElementGuid>56b634d7-5eee-44ad-a47e-727aadb01a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Orders_details.aspx?id=5072045</value>
      <webElementGuid>2a3e92bb-d891-4104-aaa8-4a3e4ff8caaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5072045</value>
      <webElementGuid>afdcf94a-ac02-4f3f-905b-baab817f7cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdMain_ctl00_ctl04_hypOrderId&quot;)</value>
      <webElementGuid>819259fb-96da-4d71-8377-b15618d6d61a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_hypOrderId']</value>
      <webElementGuid>6f2bd1c5-76fb-4af9-a3c1-fae7de9958ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdMain_ctl00__0']/td[4]/a</value>
      <webElementGuid>f9b7cfc5-983b-41eb-ba8c-3f2e426f5dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'5072045')]</value>
      <webElementGuid>ca63385c-7e5e-4650-a122-a25cb76b77f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[39]/following::a[1]</value>
      <webElementGuid>05ca44c7-473b-4653-bd76-251918272210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dummyperson123@mysite.com'])[1]/preceding::a[2]</value>
      <webElementGuid>3c6dd06e-9806-492d-bb6b-2b1ab865c63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dummy Person'])[1]/preceding::a[3]</value>
      <webElementGuid>0d3cdb5c-3ac3-4c26-8d74-9182f4bf3412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5072045']/parent::*</value>
      <webElementGuid>b0f0d4c9-4f57-4ea0-bb20-e338b3e2b029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Orders_details.aspx?id=5072045')]</value>
      <webElementGuid>e637e89d-3c84-47d6-9c35-61ee80976cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>d65b4a71-2454-48c8-bf7e-caca57fd1727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ContentPlaceHolder1_grdMain_ctl00_ctl04_hypOrderId' and @href = 'Orders_details.aspx?id=5072045' and (text() = '5072045' or . = '5072045')]</value>
      <webElementGuid>daca081a-ae8d-4f32-8cea-bd7f3f3470c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
