<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_get ordernumber</name>
   <tag></tag>
   <elementGuidId>d339555b-5f59-48ae-89ae-363ca376a64e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='SiteMapPath1']/span[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>426d7d3f-a2bf-4e59-a722-a2ddd69bc793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order No: 5069952</value>
      <webElementGuid>2a587d59-dc60-40d3-8b6d-ce521e0a9daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteMapPath1&quot;)/span[5]</value>
      <webElementGuid>e33378c9-d494-406f-b807-c707f2272d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='SiteMapPath1']/span[5]</value>
      <webElementGuid>5954e82b-07a9-4c5e-8959-672c11c596a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[2]/following::span[1]</value>
      <webElementGuid>1061ee79-202e-4222-8ec5-7e54584e5dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Orders'])[3]/following::span[2]</value>
      <webElementGuid>92fe2dc6-a624-4cb0-9bd3-dda9fd30d554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Status'])[1]/preceding::span[1]</value>
      <webElementGuid>fa3b9d60-b914-4839-9029-ebfc38698fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample'])[1]/preceding::span[1]</value>
      <webElementGuid>a2fad0a0-ed7f-4e68-ab9c-8deaaee38e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Order No: 5069952']/parent::*</value>
      <webElementGuid>108e135a-1dd5-4485-8b40-1e6a27e7c1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[5]</value>
      <webElementGuid>641a21e9-5645-4ade-bd0e-3e1c841d51a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Order No: 5069952' or . = 'Order No: 5069952')]</value>
      <webElementGuid>3fd8dddd-af2d-45fc-8fb4-a3f362cee3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
