<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Copy_Billing_ShitTo</name>
   <tag></tag>
   <elementGuidId>ac05c8ad-c327-43d3-aaa5-7ef69bce0cb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnCopyBillingToShipping</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnCopyBillingToShipping']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3a37ef4-859b-4dc7-8dd7-ed455593ad38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCopyBillingToShipping</value>
      <webElementGuid>e5fecd6c-5dce-4d5e-8ca7-c82a623db7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copy Billing</value>
      <webElementGuid>8bc44fca-1016-4a69-a2ea-3fe2c5db212e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCopyBillingToShipping&quot;)</value>
      <webElementGuid>3b3c8d60-dcfe-4505-bea8-ba2ea3328abc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnCopyBillingToShipping']</value>
      <webElementGuid>64e5a518-1204-4501-a995-0a2ba544c7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlCreateOrder']/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[7]/td/table/tbody/tr/td[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>aa3e25ff-e238-49a3-a4dc-70fc4b3b6c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Copy Billing')]</value>
      <webElementGuid>5ff93d97-a0c9-428a-bae5-53ffcc9ca908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ship To'])[1]/following::a[1]</value>
      <webElementGuid>e7698a08-5061-4577-805a-5e3cea47a5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy From Account'])[1]/following::a[1]</value>
      <webElementGuid>e638f921-bd75-4c7d-a575-d50289c972b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/preceding::a[1]</value>
      <webElementGuid>43dad6bb-44ad-440c-ac69-aab6e34f34e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First, MI'])[1]/preceding::a[1]</value>
      <webElementGuid>439691a9-cbc2-4aaf-8719-c0c07635cf27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copy Billing']/parent::*</value>
      <webElementGuid>46327b02-06c2-4a87-b4da-3f692adb8c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/table/tbody/tr/td[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>f9957aea-82f8-49e2-98ea-b6879e4cd60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnCopyBillingToShipping' and (text() = 'Copy Billing' or . = 'Copy Billing')]</value>
      <webElementGuid>3d84ff60-0e1c-4682-81f0-9c5b847b9c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
