<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Orders</name>
   <tag></tag>
   <elementGuidId>96086278-6c42-40b8-aa60-0cc571d00945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mnuMainOrders</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mnuMainOrders']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67796e25-32e4-48fb-b3fb-7b296e33f9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rmLink rmRootLink rmFocused rmSelected rmClicked rmExpanded</value>
      <webElementGuid>d99ca8a5-d4ba-4f60-a28c-fa0fe00feeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mnuMainOrders</value>
      <webElementGuid>bfa598b1-dc8b-4722-93e3-cfa923d93cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ManageOrders.aspx?filters=cleared</value>
      <webElementGuid>586ca336-92d7-4932-b36e-4ac2c431b8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orders</value>
      <webElementGuid>f7f05452-fd0a-4bbc-a147-490d2acd81b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mnuMainOrders&quot;)</value>
      <webElementGuid>1bf0ae0c-32ab-4380-9a71-640c9411e8da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mnuMainOrders']</value>
      <webElementGuid>a9904316-90f6-45e2-98c6-03ce77752452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mnyMain']/ul/li[4]/a</value>
      <webElementGuid>f1a9b1a8-a767-4227-a563-d25a0a909807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channel Customers'])[1]/following::a[1]</value>
      <webElementGuid>ce26a14b-55be-4d99-9c31-60cfdc7d83ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Customers'])[1]/following::a[2]</value>
      <webElementGuid>69f6b8d3-99c8-486c-b659-1835a7d43ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Orders'])[1]/preceding::a[1]</value>
      <webElementGuid>5512266b-0131-47d5-9438-6d5274bf7b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'ManageOrders.aspx?filters=cleared')]</value>
      <webElementGuid>29dcc6e3-ab70-4732-a792-5bed95b92cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>b2dd6aa2-c1c1-4ddf-9837-6c38115c7815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'mnuMainOrders' and @href = 'ManageOrders.aspx?filters=cleared' and (text() = 'Orders' or . = 'Orders')]</value>
      <webElementGuid>5f64fe73-8037-4a1f-ac48-65a73546c637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
