<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First_BillingAddssFirstNameField</name>
   <tag></tag>
   <elementGuidId>98fba9bf-041f-4c1e-851a-9474d0822eba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_BillingAddss_FirstNameField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_BillingAddss_FirstNameField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d49bb555-a818-4039-9a71-f5ed1e56684f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$BillingAddss$FirstNameField</value>
      <webElementGuid>8ba3f5ed-b98e-4e70-a19f-23296f5055d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f90707c0-53c1-4454-a86d-edc9540ca079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2f95cb63-67ea-4ffc-b7df-f515cf5a5739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_BillingAddss_FirstNameField</value>
      <webElementGuid>ad168606-75af-4cc5-8349-c68487c1bf1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_BillingAddss_FirstNameField&quot;)</value>
      <webElementGuid>a6f9bf4a-73a5-43ff-8eb8-3a49a26a3bbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_BillingAddss_FirstNameField']</value>
      <webElementGuid>80a63e4e-d0de-499a-ae71-b1ff0fed9c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_BillingAddss_trNameFirstMi']/td[2]/input</value>
      <webElementGuid>8c74318d-d1bd-454a-b34f-79e183bda456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>bf73c338-3866-4e28-a219-d4dfed2fd627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$BillingAddss$FirstNameField' and @type = 'text' and @id = 'ContentPlaceHolder1_BillingAddss_FirstNameField']</value>
      <webElementGuid>b16ba586-c1f6-43a7-ac6f-d697e06aca8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
