<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_chkIsQuoteOrder</name>
   <tag></tag>
   <elementGuidId>38f53887-7b1b-4d07-bab0-f39d3df8867b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_chkIsQuoteOrder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_chkIsQuoteOrder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93ce253d-a8ab-4b2f-aff3-0d02ef9f92ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_chkIsQuoteOrder</value>
      <webElementGuid>6e226445-690f-4c33-8f8a-b27cfde142cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a001bae5-0c37-4dc2-a646-75fcdc429408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$chkIsQuoteOrder</value>
      <webElementGuid>b5b7df0b-cd57-4ff5-9c0d-803907081dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_chkIsQuoteOrder&quot;)</value>
      <webElementGuid>84b7d389-6e34-4b20-a9ec-be04a1dd31d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_chkIsQuoteOrder']</value>
      <webElementGuid>c3b43b8e-9d43-4af3-a550-30e17e1a257f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlCreateOrder']/table/tbody/tr/td/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>d1417f2a-84bb-4ba0-9d3b-3bb55f945e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>1de633e0-4c31-4757-b2ef-a8dad46e580a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_chkIsQuoteOrder' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$chkIsQuoteOrder']</value>
      <webElementGuid>60b55a1a-b414-498d-9e76-9fb3e3ddbc9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
