<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Instructions_txtCustomerInstructions_OtherInfo</name>
   <tag></tag>
   <elementGuidId>e9ee890e-3141-47a9-a9c1-196c5bd925c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_txtCustomerInstructions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_txtCustomerInstructions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d344cdd0-91fe-46f3-ae92-489b51c16446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$txtCustomerInstructions</value>
      <webElementGuid>279a6f6e-d9db-4355-a1b3-bfaed1036276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c8d7966-7269-48ef-9569-33425474fb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_txtCustomerInstructions</value>
      <webElementGuid>d7ab61d9-ac0e-40aa-851d-5cb3aafe18f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_txtCustomerInstructions&quot;)</value>
      <webElementGuid>11170ac9-6543-4377-ac1a-be1688320c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_txtCustomerInstructions']</value>
      <webElementGuid>09be65f0-7da2-4728-8d32-db4df525e12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlCreateOrder']/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[8]/td/table/tbody/tr[2]/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>d9251815-0459-4617-88eb-7e6a69f541b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/table/tbody/tr[2]/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>03587ae7-c59b-4b70-92cb-2c22051cb7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$txtCustomerInstructions' and @type = 'text' and @id = 'ContentPlaceHolder1_txtCustomerInstructions']</value>
      <webElementGuid>f1465a1d-7517-4900-93bf-0f6916f08d8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
