<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StateZip_BillingAddssPostalCodeField</name>
   <tag></tag>
   <elementGuidId>85eda057-ea94-4b6e-a867-c656bba8d59c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_BillingAddss_PostalCodeField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_BillingAddss_PostalCodeField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f51b8b8-4d83-4bfe-bbce-2489608faccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$BillingAddss$PostalCodeField</value>
      <webElementGuid>01c1ec83-db7d-4314-9705-72ea27d3ad71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d251b174-e8df-4a5d-b720-43541688812e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>dcf2a611-e274-4043-a0fd-9bcca60c5b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_BillingAddss_PostalCodeField</value>
      <webElementGuid>e0d51d82-689d-4a71-8d23-77d165ba4f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_BillingAddss_PostalCodeField&quot;)</value>
      <webElementGuid>184cf2be-2bf3-4754-b4d2-b6866623fd1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_BillingAddss_PostalCodeField']</value>
      <webElementGuid>8a14e0d9-7c7f-42c3-8a56-ff8e8a2310cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ContentPlaceHolder1_BillingAddss_tdZip']/input</value>
      <webElementGuid>53724701-cecc-462d-b3aa-bff3d893da6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/input</value>
      <webElementGuid>569ae225-dc49-464d-9758-04606cd7be3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$BillingAddss$PostalCodeField' and @type = 'text' and @id = 'ContentPlaceHolder1_BillingAddss_PostalCodeField']</value>
      <webElementGuid>f4d843a1-9019-4d23-9e7e-2e3db4e82ada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
