<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last_BillingAddssLastNameField</name>
   <tag></tag>
   <elementGuidId>e90e5f2a-dce4-4d4e-b6e6-e4e12fc6f73a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_BillingAddss_LastNameField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_BillingAddss_LastNameField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>761d5ca1-68b1-4626-a340-cab413939a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$BillingAddss$LastNameField</value>
      <webElementGuid>cb983702-2e4a-4855-a749-afb74289468b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc0d1ff8-4991-4e81-8d91-51d15d17cd75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7e0bf700-0cd9-4a5e-8bae-a0b4224a6503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_BillingAddss_LastNameField</value>
      <webElementGuid>8be12cb3-70f9-4968-bf86-88ee65f7426b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_BillingAddss_LastNameField&quot;)</value>
      <webElementGuid>74e2a278-481a-450e-8c07-67df3dddafed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_BillingAddss_LastNameField']</value>
      <webElementGuid>388ee45f-8e7c-47ab-b2a3-64e05a9c0df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_BillingAddss_trNameLast']/td[2]/input</value>
      <webElementGuid>accabf04-dd38-4d41-93cc-2fe95f952090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>2acd3970-9d0f-44e3-b521-709f22ac71b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$BillingAddss$LastNameField' and @type = 'text' and @id = 'ContentPlaceHolder1_BillingAddss_LastNameField']</value>
      <webElementGuid>d1657792-2a3d-438c-8fe2-b530c9a4b2f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
