<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First_ShippingAddressFirstNameField</name>
   <tag></tag>
   <elementGuidId>6d78af73-79f1-4026-b284-d49b55514d72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ShippingAddress_FirstNameField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ShippingAddress_FirstNameField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13901f7e-dc82-451b-822d-0a6a0ee0a3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ShippingAddress$FirstNameField</value>
      <webElementGuid>eec16304-7449-4029-9bf2-975e4f67abd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>723e9c95-71b7-4357-a312-ceba956830bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>sfsf</value>
      <webElementGuid>9a68173d-1a29-47d4-a57b-8a6cded833f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c6a93fc6-740f-4029-b6c0-3b4840ccc050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ShippingAddress_FirstNameField</value>
      <webElementGuid>2feef1be-1843-4f85-beb1-59dde72748f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ShippingAddress_FirstNameField&quot;)</value>
      <webElementGuid>afcc4ea8-6ae8-4f6c-b71d-fe48e44fb018</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ShippingAddress_FirstNameField']</value>
      <webElementGuid>d74e839c-c5ee-4d7f-b84f-0b690180ea60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_ShippingAddress_trNameFirstMi']/td[2]/input</value>
      <webElementGuid>8c9241b6-d6af-4b28-8076-5823bc470b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>7b018639-54c8-4cb3-a2cf-fe8abb61dbb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$ShippingAddress$FirstNameField' and @type = 'text' and @id = 'ContentPlaceHolder1_ShippingAddress_FirstNameField']</value>
      <webElementGuid>7e9030d6-b61f-4768-ae43-edc739dceba8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
