<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_ShippingAddressPhoneField</name>
   <tag></tag>
   <elementGuidId>eec97240-b734-400c-a367-b4114c8bb39f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ShippingAddress_PhoneField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ShippingAddress_PhoneField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3ce8352-f8bc-4451-8442-f3396ea749c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ShippingAddress$PhoneField</value>
      <webElementGuid>ed08e3e5-9189-4edc-8dd6-e649d2636dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7392ee2-20ff-40e2-aeb0-8efc8fc4f137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>54353434535</value>
      <webElementGuid>1e0c5c4b-5c73-4731-b645-1fbb596a16f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>87ba60e2-ba85-4854-8514-fe2d2f546a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ShippingAddress_PhoneField</value>
      <webElementGuid>60cccdab-a846-4d49-9e14-bf25817992d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ShippingAddress_PhoneField&quot;)</value>
      <webElementGuid>cef30bf1-38bf-41d6-affe-818181e964db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ShippingAddress_PhoneField']</value>
      <webElementGuid>339a078c-0c4e-44d0-9ca6-153994302440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_ShippingAddress_trPhone']/td[2]/input</value>
      <webElementGuid>2445e4ff-11c1-4d20-ba3b-03f36c0d2442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>05e57f66-7d05-4c0c-99ea-d0012acade25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$ShippingAddress$PhoneField' and @type = 'text' and @id = 'ContentPlaceHolder1_ShippingAddress_PhoneField']</value>
      <webElementGuid>2dbae216-21e1-4e99-ab20-5c25d8042896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
