<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_ShippingAddressCityField</name>
   <tag></tag>
   <elementGuidId>f4692e18-5ba4-48b7-9759-c161b9289b46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ShippingAddress_CityField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ShippingAddress_CityField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7988a32-ab8d-4963-8ec9-4314245c7980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ShippingAddress$CityField</value>
      <webElementGuid>6dd42bbc-2d2c-41fa-adcd-de70e940cb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfcbd1be-81fc-403c-a294-091f9eba738f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>sdf</value>
      <webElementGuid>e38135fb-9fff-495b-8463-2652b8e495c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b4688db7-f5df-4569-ac7b-8d14ae0bd313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ShippingAddress_CityField</value>
      <webElementGuid>96201b3f-b62e-4ea2-84d2-2107ed0efafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ShippingAddress_CityField&quot;)</value>
      <webElementGuid>09b83c04-1987-44f8-97e8-ba7e636ed075</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ShippingAddress_CityField']</value>
      <webElementGuid>fa6a0fc7-9aaf-4d90-a6b7-8ae06cc79a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_ShippingAddress_trCity']/td[2]/input</value>
      <webElementGuid>8318ba86-3c5f-4f06-ae56-11ee39dc9886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>4942833d-5a98-4dae-9382-3e41312521c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$ShippingAddress$CityField' and @type = 'text' and @id = 'ContentPlaceHolder1_ShippingAddress_CityField']</value>
      <webElementGuid>13b01473-2c52-4817-a852-0c405ad3f44c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
