<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StateZip_ShippingAddressPostalCodeField</name>
   <tag></tag>
   <elementGuidId>fa9bb097-ebd1-4314-8d24-22bf339f0aa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ShippingAddress_PostalCodeField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ShippingAddress_PostalCodeField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef0e6bbf-a5a7-44fa-91f0-f31b614c6c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ShippingAddress$PostalCodeField</value>
      <webElementGuid>ac3d7d43-e004-4732-9fd7-850049f30ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>694e29aa-4f63-4c6e-8851-54444dd868cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>3a8f149b-3f52-4148-8cbf-add900c8174e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ShippingAddress_PostalCodeField</value>
      <webElementGuid>040dbfde-ea8c-421c-8265-60941b2f8ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ShippingAddress_PostalCodeField&quot;)</value>
      <webElementGuid>14b1f303-1f75-4394-ba09-81e2978b5d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ShippingAddress_PostalCodeField']</value>
      <webElementGuid>c1d2c31e-2a0c-4bc6-aadf-3a7c2fb9d5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ContentPlaceHolder1_ShippingAddress_tdZip']/input</value>
      <webElementGuid>d7789df1-745c-48ba-a038-88b4d2cf4ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>b7335689-1bb9-424a-bb3e-e633b679619a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$ShippingAddress$PostalCodeField' and @type = 'text' and @id = 'ContentPlaceHolder1_ShippingAddress_PostalCodeField']</value>
      <webElementGuid>0d4adeeb-4e5f-4da3-9116-491ff2effca0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
