<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Company_frst</name>
   <tag></tag>
   <elementGuidId>fef1bbd1-dc3a-4571-be7b-54559c351183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ddlCompany</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ContentPlaceHolder1_ddlCompany']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>44250dd9-28bb-483c-8a9a-7cdca055d65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ddlCompany</value>
      <webElementGuid>e0ea2f56-7c7f-4b73-90ea-83eeb7d832ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$ContentPlaceHolder1$ddlCompany\',\'\')', 0)</value>
      <webElementGuid>f4c3a028-e512-49b3-bdc4-71518656b6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ddlCompany</value>
      <webElementGuid>68cf6e98-fa90-4e2c-b4f3-643adc9d4dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			Select
			canada-comp
			Imrancompany
			Imrancompany1
			ImrancompanyTesting
			Khurramcomp
			Live Client
			Sellercloud

		</value>
      <webElementGuid>b6d46364-a182-47fb-a616-71233457a3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ddlCompany&quot;)</value>
      <webElementGuid>8b025bfa-17f1-4233-be58-1a77def939df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ContentPlaceHolder1_ddlCompany']</value>
      <webElementGuid>e22e3405-a716-405b-92ce-f739163b7592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlCreateOrder']/table/tbody/tr/td/table/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>97e3243a-4e5e-47e1-be39-c9810024208d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company:'])[1]/following::select[1]</value>
      <webElementGuid>c4b7b563-f691-484c-a41c-c9359143e2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Order'])[3]/following::select[1]</value>
      <webElementGuid>65273938-8c74-4842-8a70-5335982bcff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This order is wholesale Order'])[1]/preceding::select[1]</value>
      <webElementGuid>d8a96305-f87f-47e5-b5ad-bcec3a842a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This order is Sample Order'])[1]/preceding::select[1]</value>
      <webElementGuid>b96c83b2-f0b3-4245-94ed-d49832c5c680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>46a8f423-11c5-4b6f-8d4e-63b2a584d70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder1$ddlCompany' and @id = 'ContentPlaceHolder1_ddlCompany' and (text() = '
			Select
			canada-comp
			Imrancompany
			Imrancompany1
			ImrancompanyTesting
			Khurramcomp
			Live Client
			Sellercloud

		' or . = '
			Select
			canada-comp
			Imrancompany
			Imrancompany1
			ImrancompanyTesting
			Khurramcomp
			Live Client
			Sellercloud

		')]</value>
      <webElementGuid>5b9b9fd1-fda7-4f8a-a81e-5044af4efa91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
