<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create New Order_chk</name>
   <tag></tag>
   <elementGuidId>ea501a53-be28-45ba-af68-f1f63e35f3e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='SiteMapPath1']/span[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be217ff7-3472-435a-a2ac-7b4ce70a9521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New Order</value>
      <webElementGuid>731c1b51-ca6f-4cfb-88db-5618df733ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteMapPath1&quot;)/span[5]</value>
      <webElementGuid>d5d91add-473d-4e10-862e-e042fd015c4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='SiteMapPath1']/span[5]</value>
      <webElementGuid>de3aacbc-89e8-4608-a0e1-918ded2da2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[2]/following::span[1]</value>
      <webElementGuid>a896130c-1922-44a9-90aa-fe6c42307373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Orders'])[3]/following::span[2]</value>
      <webElementGuid>a6eb47ff-fe82-48f4-9168-ff00414838be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company:'])[1]/preceding::span[1]</value>
      <webElementGuid>5682f3cc-1e98-494e-aee6-585ae72443c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This order is wholesale Order'])[1]/preceding::span[1]</value>
      <webElementGuid>56f0392a-72ba-4357-8241-f5c88baa33d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]</value>
      <webElementGuid>0bbd3765-b96a-46e8-a2b0-b0282f4c78e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Create New Order' or . = 'Create New Order')]</value>
      <webElementGuid>3026608e-e973-444f-afa5-9da79ffa3ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
