<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comments_txtCustomerAccountNotes_CustomerRtng</name>
   <tag></tag>
   <elementGuidId>90ab3387-127e-4fa8-815b-a71176c82839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_txtCustomerAccountNotes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ContentPlaceHolder1_txtCustomerAccountNotes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2b361bac-84d6-48a5-b6e7-b9b789d50178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$txtCustomerAccountNotes</value>
      <webElementGuid>5ee660c5-7a4b-4bca-9f52-fc9429fb30f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e8d80b09-b77c-4551-b95e-6c6b4dee7feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>66b1a234-3827-4d7f-9e22-6fc3adb5f8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_txtCustomerAccountNotes</value>
      <webElementGuid>3c5af8d9-abe6-4125-b4fb-bcde0fd310ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_txtCustomerAccountNotes&quot;)</value>
      <webElementGuid>8ef9695f-6467-43f6-8ebd-28f276f350af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ContentPlaceHolder1_txtCustomerAccountNotes']</value>
      <webElementGuid>b3f08f0b-ffc2-4806-b9e4-477e7c68932c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlCreateOrder']/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[8]/td[2]/table/tbody/tr[3]/td/textarea</value>
      <webElementGuid>c2b6eaa1-9057-4e8e-bedc-e8972533ad92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/textarea</value>
      <webElementGuid>57a546d7-37fe-4ed9-919a-3984c2c2dac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$ContentPlaceHolder1$txtCustomerAccountNotes' and @id = 'ContentPlaceHolder1_txtCustomerAccountNotes']</value>
      <webElementGuid>643b6c39-8cec-4070-a244-aff5157cde2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
