<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Order Notes_1tbOrderNotes</name>
   <tag></tag>
   <elementGuidId>e127ef86-83d6-42c2-8562-45db6b44ab6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_tbOrderNotes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ContentPlaceHolder1_tbOrderNotes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>69ec78ee-e385-4890-bebd-9319af87ab42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$tbOrderNotes</value>
      <webElementGuid>c1d69a3c-5637-4460-8731-5564902eca34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b41eba97-d4b9-4489-9335-f6b47f8a5a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>fe4c7ea1-a970-4239-9758-d3daf6c02c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_tbOrderNotes</value>
      <webElementGuid>3a935d5a-34b2-49c3-985f-f09f033de3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_tbOrderNotes&quot;)</value>
      <webElementGuid>f9b771bf-b3aa-4459-9f9c-405d70e1a8c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ContentPlaceHolder1_tbOrderNotes']</value>
      <webElementGuid>d83f3e62-d6eb-4764-a6e0-f65977e7a56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlCreateOrder']/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[8]/td/table/tbody/tr[2]/td/table/tbody/tr[7]/td/textarea</value>
      <webElementGuid>f8719e76-dceb-4bb5-8f7b-5bf8fa2f64f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>09b17852-72f5-43fc-bdc9-7c76e8699171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$ContentPlaceHolder1$tbOrderNotes' and @id = 'ContentPlaceHolder1_tbOrderNotes']</value>
      <webElementGuid>871ba713-8678-4609-a5eb-bab6344b0124</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
