<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnShowHistory2</name>
   <tag></tag>
   <elementGuidId>6c4dfddc-bfcf-4e54-9a3f-b44a07367336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_Order_ChangeHistory1_btnShowHistory2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_Order_ChangeHistory1_btnShowHistory2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d6a0609-af6b-488b-89a6-7ae1ed4068bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>db32d446-60f2-4248-ace2-c92b0050ab8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$Order_ChangeHistory1$btnShowHistory2</value>
      <webElementGuid>954ee549-aabf-47b6-88e7-41fc2760a46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_Order_ChangeHistory1_btnShowHistory2</value>
      <webElementGuid>e29b75c5-3232-44b5-9b21-a3c2133ea269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/app/ShowHistory.jpg</value>
      <webElementGuid>06647aad-4f81-493a-97c2-4c92e9b3afb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.open('/Orders/Orders_ChangeHistoryFull.aspx?id=5074176', '_blank'); return false;</value>
      <webElementGuid>74836141-d8ec-4f61-8d73-0b3b74c071aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_Order_ChangeHistory1_btnShowHistory2&quot;)</value>
      <webElementGuid>aff05c38-fe9c-4786-92f6-21759f15edb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_Order_ChangeHistory1_btnShowHistory2']</value>
      <webElementGuid>ad544930-1f62-4586-822e-87aa18df1651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/table/tbody/tr[4]/td[2]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr[9]/td/table/tbody/tr/td/input</value>
      <webElementGuid>f5ab9499-5326-41fb-a917-fd48b9e362a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td/table/tbody/tr/td/input</value>
      <webElementGuid>9bb3d00a-aa6a-4d04-8a1d-134fcd4e5438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$Order_ChangeHistory1$btnShowHistory2' and @id = 'ContentPlaceHolder1_Order_ChangeHistory1_btnShowHistory2' and @src = '/images/app/ShowHistory.jpg']</value>
      <webElementGuid>5bd8fd09-9e1c-4ff1-8685-14862cba5fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
