<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnClose</name>
   <tag></tag>
   <elementGuidId>f0f5e473-f7bc-4ba3-a626-4cde02293311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnClose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnClose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2443341-c339-4928-9e7f-e7dd3fa72e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c348335b-6a68-40fb-b1fa-2e8b0ff31f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnClose</value>
      <webElementGuid>27040e5d-278a-460d-a157-a108268c20c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Close Window</value>
      <webElementGuid>110a25a5-a0c0-4341-8530-eea67aff3c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.close();</value>
      <webElementGuid>ab71b87c-bf85-48f3-be02-ca61d7bc51a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnClose</value>
      <webElementGuid>2daf8e4f-f463-4d45-a976-aaa3f2514571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnClose&quot;)</value>
      <webElementGuid>a2b72875-1913-4bcc-a3c9-4a8d818e1e3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnClose']</value>
      <webElementGuid>3464bc38-aa61-4c2a-aa57-94c1eba2ed62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/table/tbody/tr[7]/td/input</value>
      <webElementGuid>a1c51d55-6b4d-486c-b2d9-c69d4f79c98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/input</value>
      <webElementGuid>abd9b70e-f318-4f5c-9294-66423d235d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnClose' and @id = 'btnClose']</value>
      <webElementGuid>3475bae0-e4f7-4944-a062-0d028ba5d1c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
