<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number_txtCardNumber</name>
   <tag></tag>
   <elementGuidId>f4907f5b-0e87-4eb1-8d0b-492b75013a10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_txtCardNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_txtCardNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7dc836d-f002-4cdc-95b9-023da975614c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$txtCardNumber</value>
      <webElementGuid>715dd82f-3729-4e33-a53d-667997751e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17d84223-33fe-4936-ab74-5c1065597af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_txtCardNumber</value>
      <webElementGuid>7ea45d62-86d5-4447-a2ae-0a3cc17cbf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_txtCardNumber&quot;)</value>
      <webElementGuid>10a10419-4c65-41b0-ae89-eecb7a81eff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_txtCardNumber']</value>
      <webElementGuid>8730a1c1-f641-4648-9a37-6093a59dd6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trPaymentCC']/td/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>01b6bce1-d3bd-4d6c-ac3c-8d5a12924d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>97d7c097-c9b0-471a-ba46-c21fe6d0a83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$txtCardNumber' and @type = 'text' and @id = 'ContentPlaceHolder1_txtCardNumber']</value>
      <webElementGuid>c5d28be1-98bd-4bf2-80df-8e55b1eac382</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
