<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_QtyToMove</name>
   <tag></tag>
   <elementGuidId>6b1bd5a5-18f3-4b65-8e4f-7e1644dd8a3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyToMove</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyToMove']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9e4994b-e881-4c61-8b94-0f5770adcaaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdItems$ctl00$ctl04$txtQtyToMove</value>
      <webElementGuid>fe16974a-1d8a-4f91-8eb7-e0b81b6126d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c49136c-91fb-4a05-88e5-cb460e62bb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyToMove</value>
      <webElementGuid>2a6960fb-204d-4ffd-a634-8aee0bc3c08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyToMove&quot;)</value>
      <webElementGuid>b42b819e-8385-4962-a8e5-5709228cc0d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyToMove']</value>
      <webElementGuid>5b1e24a4-e21c-4d20-8963-4b66fdb7a9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdItems_ctl00__0']/td[8]/input</value>
      <webElementGuid>cc626f21-fa99-47ae-913f-397588609f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>f92d135b-c51f-488b-a843-0ed802bc2077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$grdItems$ctl00$ctl04$txtQtyToMove' and @type = 'text' and @id = 'ContentPlaceHolder1_grdItems_ctl00_ctl04_txtQtyToMove']</value>
      <webElementGuid>087166d6-fc6f-486e-b686-82f373c7f823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
