<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SelectCheckBox</name>
   <tag></tag>
   <elementGuidId>5592c525-8b47-4110-ae5c-879f57fd7869</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdItems_ctl00_ctl04_columnSelectCheckBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdItems_ctl00_ctl04_columnSelectCheckBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc7d77d3-5b77-4d58-bc06-a12c161b5265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdItems_ctl00_ctl04_columnSelectCheckBox</value>
      <webElementGuid>b2e8cb6d-3972-4237-b551-bfa8dc7f2d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3352e288-fe9b-4ee5-aee5-7fe972c128a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdItems$ctl00$ctl04$columnSelectCheckBox</value>
      <webElementGuid>fb5757fd-a2db-4c99-b71a-0704542d5dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdItems_ctl00_ctl04_columnSelectCheckBox&quot;)</value>
      <webElementGuid>edad8ea9-737b-4788-8901-647a33e456ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdItems_ctl00_ctl04_columnSelectCheckBox']</value>
      <webElementGuid>22a60338-3bd0-46f9-94dc-3918e599e553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdItems_ctl00__0']/td[2]/input</value>
      <webElementGuid>a5324641-597b-4124-9365-28adf9133cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>fc37ce60-e79e-404c-9e08-f800a38ba04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_grdItems_ctl00_ctl04_columnSelectCheckBox' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$grdItems$ctl00$ctl04$columnSelectCheckBox']</value>
      <webElementGuid>35a946e4-f105-4398-8cd0-e254286ad438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
