<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OrderSplitedRslt</name>
   <tag></tag>
   <elementGuidId>162a2c65-cf5f-4f7c-ba31-7cce7b7ad990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_lblOrderId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_lblOrderId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3a1f4f3-b18a-41e1-b484-6ce2c066d9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_lblOrderId</value>
      <webElementGuid>9c718492-69b1-4edf-bed6-0cffcc6061a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5074165 (5074164)</value>
      <webElementGuid>6b4c94c7-efc3-493e-8a33-d097d2265b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_lblOrderId&quot;)</value>
      <webElementGuid>f7080b47-9ec6-4ffb-8f93-c0258895cf72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_lblOrderId']</value>
      <webElementGuid>328c4d3d-ee5f-476f-8ae1-ea73c7b1e239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlLazyOrderID']/table/tbody/tr[4]/td[2]/span</value>
      <webElementGuid>02a59fe3-6a35-4bd4-b8c8-ed744f9ea338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order #:'])[1]/following::span[1]</value>
      <webElementGuid>064aa43a-7feb-4554-9cb5-bc6dce15a841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khurramcomp'])[1]/following::span[1]</value>
      <webElementGuid>55fa2307-a4e2-460f-a42c-2a248a920776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Date:'])[1]/preceding::span[1]</value>
      <webElementGuid>88841ee6-8a82-4569-a598-87071cb623ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channel:'])[1]/preceding::span[2]</value>
      <webElementGuid>4c69df74-08dc-419b-9f6d-4fe475cb0f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5074165 (']/parent::*</value>
      <webElementGuid>5059cf45-4cd0-4b0d-9edf-372549340e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/table/tbody/tr[4]/td[2]/span</value>
      <webElementGuid>f77983b4-cefb-4360-8b38-21f48b7d4142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_lblOrderId' and (text() = '5074165 (5074164)' or . = '5074165 (5074164)')]</value>
      <webElementGuid>64f959cf-0033-4a91-aa65-78c391d2a6ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
