<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_product_btnDelete</name>
   <tag></tag>
   <elementGuidId>a2ac980d-086b-4e3e-a2e0-d902af07442d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_NonPackageItems_btnDelete_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_NonPackageItems_btnDelete_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abe382b8-3efa-4ff9-b17a-c7c79c19d0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ff84e403-668f-4b2e-99df-63a88500a379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$NonPackageItems$ctl02$btnDelete</value>
      <webElementGuid>38d716b2-79b2-485d-a061-6365d8c307bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_NonPackageItems_btnDelete_0</value>
      <webElementGuid>21dd6d39-d591-4a8a-a790-8c3638a0da3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/buttons/admin/buttons/x.gif</value>
      <webElementGuid>cc194001-182c-4a94-a642-773966c7a80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Are you sure you want to delete this item?');WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder1$NonPackageItems$ctl02$btnDelete&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>5e1546da-776b-47dd-acb5-9853b4ecb466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_NonPackageItems_btnDelete_0&quot;)</value>
      <webElementGuid>78b5a089-017f-473d-b303-3ff36e0399b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_NonPackageItems_btnDelete_0']</value>
      <webElementGuid>6b5d52d2-a876-49cc-b9e9-9764b935a658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ContentPlaceHolder1_NonPackageItems']/tbody/tr[2]/td[13]/input</value>
      <webElementGuid>9119ed31-b5de-461b-92e8-baaa0fbc2ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[13]/input</value>
      <webElementGuid>9697c35f-1858-4d94-a368-90c366df7760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$NonPackageItems$ctl02$btnDelete' and @id = 'ContentPlaceHolder1_NonPackageItems_btnDelete_0' and @src = '../images/buttons/admin/buttons/x.gif']</value>
      <webElementGuid>5f32ec6b-d84e-4bb1-9a07-61678430a0f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
