<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify Tax percent</name>
   <tag></tag>
   <elementGuidId>62b498f1-87cd-4306-9fe0-5438b5b5013b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_lblTaxRate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_lblTaxRate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a40814ab-dc31-42a6-95ef-ba4b00f65985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_lblTaxRate</value>
      <webElementGuid>c3cc6286-3a3b-4edf-a998-a2e52781ad2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BVSmallText</value>
      <webElementGuid>871e5b29-5857-4ae3-b7f8-1bd052f1c66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30.000%</value>
      <webElementGuid>541cc5b9-b267-4156-93a8-0fb17644f39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_lblTaxRate&quot;)</value>
      <webElementGuid>f1c10af7-dc3a-4702-852a-0b1802512db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_lblTaxRate']</value>
      <webElementGuid>813564b8-1199-4818-9a9a-299ff9578b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_trMainRow']/td/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/span</value>
      <webElementGuid>76aec691-21da-4baf-a0aa-8b20cd433c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Discounts:'])[1]/following::span[1]</value>
      <webElementGuid>6fff2d84-43c8-4ded-ac9f-bcc9dbfa618e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$6.00'])[1]/preceding::span[1]</value>
      <webElementGuid>05aee772-cd83-4fcb-a32c-110e32063ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30.000%']/parent::*</value>
      <webElementGuid>4acc947c-edd2-4e8b-9320-e305b6c49575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[5]/td/span</value>
      <webElementGuid>b0bd62ad-1840-482c-8c2c-29fca686fc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_lblTaxRate' and (text() = '30.000%' or . = '30.000%')]</value>
      <webElementGuid>3cc7859e-cfd7-40f1-84be-5930b292ef50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
