<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OrderDtl</name>
   <tag></tag>
   <elementGuidId>7ae44584-dd0d-46ed-8027-57184f5b6581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='SiteMapPath1']/span[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9db38886-e5b3-46ec-ac91-85205fc73b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Orders/Orders_Details.aspx?ID=5074151</value>
      <webElementGuid>31282154-048b-42a7-9da8-75783429e1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order No: 5074151</value>
      <webElementGuid>d766880b-5fca-4d52-92c1-ac8f5fd84e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SiteMapPath1&quot;)/span[5]/a[1]</value>
      <webElementGuid>a317dbb0-fade-4380-bb2c-2a72a513374e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='SiteMapPath1']/span[5]/a</value>
      <webElementGuid>7bca42f8-e013-4c18-9b04-415ea587d30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Order No: 5074151')]</value>
      <webElementGuid>0342f68a-89d5-4b39-a597-2ae6e37b705f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[2]/following::a[1]</value>
      <webElementGuid>cc469c32-0d97-4adc-9f15-b615f9b1c2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Orders'])[3]/following::a[1]</value>
      <webElementGuid>d3a5a794-16e1-4f37-90e7-51cbaf3b891d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[3]/preceding::a[1]</value>
      <webElementGuid>a82eff8e-2059-4f45-8e49-e7f6e185a70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Per Case Qty'])[1]/preceding::a[1]</value>
      <webElementGuid>fa4ef70b-ad93-4a1e-8b2e-cc97f07b43d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Order No: 5074151']/parent::*</value>
      <webElementGuid>2aa96840-db4a-496c-8c50-bfab42465e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Orders/Orders_Details.aspx?ID=5074151')]</value>
      <webElementGuid>a40d391b-b954-4c05-b6a2-39e08c46b01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/a</value>
      <webElementGuid>0fd1d2cb-ed74-4404-8490-6ac42a75393b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Orders/Orders_Details.aspx?ID=5074151' and (text() = 'Order No: 5074151' or . = 'Order No: 5074151')]</value>
      <webElementGuid>231edd85-a485-415e-bea3-e3f0ef70bf8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
