<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Case_price</name>
   <tag></tag>
   <elementGuidId>ba61ea7c-8717-47d8-9c92-b582f11643ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ContentPlaceHolder1_grdItems_ctl00__0']/td[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>358c9715-2ed4-40ef-85ef-1714187849a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    C$2.00
                                                </value>
      <webElementGuid>a3200051-2f5a-43ee-a985-0c092cc65906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdItems_ctl00__0&quot;)/td[10]</value>
      <webElementGuid>cad3a83a-6347-4830-ac76-f4a5bea3781e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdItems_ctl00__0']/td[10]</value>
      <webElementGuid>201d5f5a-6340-41ba-8057-3745b5261641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$1.00'])[1]/following::td[2]</value>
      <webElementGuid>8f51e360-67e4-4bfc-a8a0-fa5e67e64dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Floor Sample Glider'])[1]/following::td[3]</value>
      <webElementGuid>9a16b779-4321-499c-b0af-8a7485af632c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$6.00'])[1]/preceding::td[3]</value>
      <webElementGuid>84a86646-c1fe-457e-bfaf-06d95801c096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Customer', &quot;'&quot;, 's Instructions:')])[1]/preceding::td[9]</value>
      <webElementGuid>64ab155e-5d7f-41dc-817b-535e1c6e17f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='C$2.00']/parent::*</value>
      <webElementGuid>9f9a38b5-6f86-4868-8cfa-2a68dbb79a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]</value>
      <webElementGuid>7b9475b5-9839-4d79-afd0-438f39436a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                    C$2.00
                                                ' or . = '
                                                    C$2.00
                                                ')]</value>
      <webElementGuid>594ac23c-4f16-4565-9859-3205c4050901</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
