<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Case_qty</name>
   <tag></tag>
   <elementGuidId>5836a6cf-5fe7-4c83-80a3-b4c5c7ab4b37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ContentPlaceHolder1_grdItems_ctl00__0']/td[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>87923ad3-d89a-4e60-a803-a42b98b29f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    3
                                                </value>
      <webElementGuid>45bb8358-f66b-4f3c-a344-ba9d42c5cbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdItems_ctl00__0&quot;)/td[11]</value>
      <webElementGuid>edee99f0-eef7-4f53-b576-4abd54c79926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdItems_ctl00__0']/td[11]</value>
      <webElementGuid>1b5640f0-2627-408f-b91f-4a57ade1166a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$2.00'])[1]/following::td[1]</value>
      <webElementGuid>c698070a-d908-4813-9bbc-11ff852cdec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$1.00'])[1]/following::td[3]</value>
      <webElementGuid>30e4ea95-6990-4413-b089-0faf0783e4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$6.00'])[1]/preceding::td[2]</value>
      <webElementGuid>3a8b2b38-0e9d-4a18-8bef-ed0f1259942a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Customer', &quot;'&quot;, 's Instructions:')])[1]/preceding::td[8]</value>
      <webElementGuid>ddb04631-2217-4ceb-8448-d38e42895957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>d3ee289e-c3a7-4181-bff8-2d8a60d694ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]</value>
      <webElementGuid>d195fba1-ade5-4c21-9388-b21ab267cbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                    3
                                                ' or . = '
                                                    3
                                                ')]</value>
      <webElementGuid>5622821d-6524-44f4-a765-0ced4bd5fb7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
