<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Confirm_Prod_DtlPage</name>
   <tag></tag>
   <elementGuidId>ee53ad8d-22c1-43bd-8e07-d069239ae479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ContentPlaceHolder1_grdItems_ctl00']/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>85c2c6c5-53ab-453e-97b5-883b7aec864a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>5b011143-1506-4a79-a82b-73bf36602474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No records to display.</value>
      <webElementGuid>d90974fc-0882-479d-af73-1ec142202832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdItems_ctl00&quot;)/tbody[1]/tr[@class=&quot;rgNoRecords&quot;]/td[2]</value>
      <webElementGuid>9bb2f55f-cb91-4504-84b8-31d96bdb1860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ContentPlaceHolder1_grdItems_ctl00']/tbody/tr/td[2]</value>
      <webElementGuid>e0e10ee5-1078-4995-80b3-87e24a63ced2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Picked'])[1]/following::td[2]</value>
      <webElementGuid>c2648b2d-c5a4-4966-9b7a-95c9b66ee6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/following::td[2]</value>
      <webElementGuid>bfe42f2b-ea17-4ee9-a962-d5a608b89707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Customer', &quot;'&quot;, 's Instructions:')])[1]/preceding::td[1]</value>
      <webElementGuid>cc458383-a676-46c6-9ded-3e5e0573cdcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/table/tbody/tr/td[2]</value>
      <webElementGuid>b396e602-862a-4cd6-a375-cbe974deefdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'No records to display.' or . = 'No records to display.')]</value>
      <webElementGuid>2488b528-4f7f-459b-9dc1-46916de08235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
