<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_getResult</name>
   <tag></tag>
   <elementGuidId>5310f65a-3a61-4d55-bbde-1acdf2453473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_pnlSettings']/table/tbody/tr/td/table/tbody/tr[2]/td/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdec6fd9-7a73-4b1c-abc4-1ce2315d56cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Message</value>
      <webElementGuid>9cfee88a-4c51-4143-ad70-73ba5bd16e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Orders 5074130 not updated because setting AllowShippingUnpaidOrders disabled on client or company level. </value>
      <webElementGuid>03672e0f-ca45-4a54-92d3-e723bb31172d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_pnlSettings&quot;)/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/div[@class=&quot;WebPageMessage&quot;]/div[@class=&quot;WebPageMessageInformation&quot;]/div[@class=&quot;Message&quot;]</value>
      <webElementGuid>99eace60-f15d-43e4-99e8-a9b3ca811ddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlSettings']/table/tbody/tr/td/table/tbody/tr[2]/td/div/div/div</value>
      <webElementGuid>837dacc6-dbf0-45e3-a5f7-aee761f6f818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved Searches'])[6]/following::div[4]</value>
      <webElementGuid>3985739a-7e76-4e1e-84d8-a9522471c6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyword'])[1]/preceding::div[1]</value>
      <webElementGuid>26f4e2c5-b719-4d47-8e78-753d485db027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU'])[1]/preceding::div[1]</value>
      <webElementGuid>e9cb5da4-55cd-4074-b076-0a1db03d92d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Orders 5074130 not updated because setting AllowShippingUnpaidOrders disabled on client or company level.']/parent::*</value>
      <webElementGuid>c9f93cd2-4431-43c6-8c5d-39acc115411b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>58b84cfc-293f-4e03-85e7-ae4440f82e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Orders 5074130 not updated because setting AllowShippingUnpaidOrders disabled on client or company level. ' or . = ' Orders 5074130 not updated because setting AllowShippingUnpaidOrders disabled on client or company level. ')]</value>
      <webElementGuid>a7c0dc99-84c7-46af-ad0f-450cf0612e58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
