<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NewChannel</name>
   <tag></tag>
   <elementGuidId>7f973e1c-10c2-430b-a978-f3d3ac321a9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ddlOrderSource</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ContentPlaceHolder1_ddlOrderSource']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fdbedc7c-ea30-4d73-9f94-b19cf6f11d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$ddlOrderSource</value>
      <webElementGuid>c9de88a3-19e4-4ac7-b6ae-64c82061b102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ddlOrderSource</value>
      <webElementGuid>caf709cf-368c-43ea-b301-4759f846cd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Select
	Amazon
	ATGStores
	BackMarket
	BedBathAndBeyond
	BestBuy
	BestBuyDS
	Bonanza
	Buy
	Cart32
	Cdiscount
	Choxi
	Direct Fulfillment
	DrugStore
	DSW
	eBayOrder
	eBaySingleItem
	ElevenMain
	Etsy
	FBA
	FingerHut
	Gilt
	GoogleExpress
	Groupon
	GrouponGateway
	GrouponMarketplace
	GS
	Hayneedle
	HomeDepot
	Houzz
	HSN
	JET
	KMart
	Kohls
	Local Store
	Magento
	MassGenie
	Meijer
	MercadoLibre
	NewEgg Business
	NewEggdotcom
	NewEggMall
	OneStopPlus
	Overstock
	PriceFalls
	PriceGrabber
	PriceMinister
	QuickBooks
	Reverb
	RMS
	SBN
	Sears
	SearsVendor
	Sharkstores
	ShopHQ
	SmartBargains
	Sonsi
	SPRichards
	StacksAndStacks
	Staples
	Tanga
	Target
	Target Plus
	TopHatter
	TradeMe
	uBid
	UnbeatableSale
	VendorCentral
	Walmart
	Walmart Marketplace
	Wayfair
	Website
	WFS
	Wholesale
	Wish
	Yahoo

</value>
      <webElementGuid>21582ffc-40fd-4374-9d3a-5ed073b55114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ddlOrderSource&quot;)</value>
      <webElementGuid>27a3c8df-0b9b-4357-81db-4c7f65a38215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ContentPlaceHolder1_ddlOrderSource']</value>
      <webElementGuid>0439b239-2b7b-432d-980f-892770126b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/table/tbody/tr[4]/td[2]/table/tbody/tr[2]/td/table/tbody/tr[4]/td/table/tbody/tr/td[2]/select</value>
      <webElementGuid>422b2b37-c58e-4ac8-b22f-7d27063b87ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channel:'])[1]/following::select[1]</value>
      <webElementGuid>9f7ef8c2-d459-4dff-9986-2c84cfda3597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Order Channel Info'])[1]/following::select[1]</value>
      <webElementGuid>16b006a5-989a-480d-b4ac-c530c26d15ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channel Order #:'])[1]/preceding::select[1]</value>
      <webElementGuid>ee715ec7-e2e1-4942-81b8-619981e2ce81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::select[1]</value>
      <webElementGuid>f2b5f8e9-e609-4fae-9e8a-71e03c6a4629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>c296d496-c11e-4ef2-8c0d-fecdf52cd9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ctl00$ContentPlaceHolder1$ddlOrderSource' and @id = 'ContentPlaceHolder1_ddlOrderSource' and (text() = '
	Select
	Amazon
	ATGStores
	BackMarket
	BedBathAndBeyond
	BestBuy
	BestBuyDS
	Bonanza
	Buy
	Cart32
	Cdiscount
	Choxi
	Direct Fulfillment
	DrugStore
	DSW
	eBayOrder
	eBaySingleItem
	ElevenMain
	Etsy
	FBA
	FingerHut
	Gilt
	GoogleExpress
	Groupon
	GrouponGateway
	GrouponMarketplace
	GS
	Hayneedle
	HomeDepot
	Houzz
	HSN
	JET
	KMart
	Kohls
	Local Store
	Magento
	MassGenie
	Meijer
	MercadoLibre
	NewEgg Business
	NewEggdotcom
	NewEggMall
	OneStopPlus
	Overstock
	PriceFalls
	PriceGrabber
	PriceMinister
	QuickBooks
	Reverb
	RMS
	SBN
	Sears
	SearsVendor
	Sharkstores
	ShopHQ
	SmartBargains
	Sonsi
	SPRichards
	StacksAndStacks
	Staples
	Tanga
	Target
	Target Plus
	TopHatter
	TradeMe
	uBid
	UnbeatableSale
	VendorCentral
	Walmart
	Walmart Marketplace
	Wayfair
	Website
	WFS
	Wholesale
	Wish
	Yahoo

' or . = '
	Select
	Amazon
	ATGStores
	BackMarket
	BedBathAndBeyond
	BestBuy
	BestBuyDS
	Bonanza
	Buy
	Cart32
	Cdiscount
	Choxi
	Direct Fulfillment
	DrugStore
	DSW
	eBayOrder
	eBaySingleItem
	ElevenMain
	Etsy
	FBA
	FingerHut
	Gilt
	GoogleExpress
	Groupon
	GrouponGateway
	GrouponMarketplace
	GS
	Hayneedle
	HomeDepot
	Houzz
	HSN
	JET
	KMart
	Kohls
	Local Store
	Magento
	MassGenie
	Meijer
	MercadoLibre
	NewEgg Business
	NewEggdotcom
	NewEggMall
	OneStopPlus
	Overstock
	PriceFalls
	PriceGrabber
	PriceMinister
	QuickBooks
	Reverb
	RMS
	SBN
	Sears
	SearsVendor
	Sharkstores
	ShopHQ
	SmartBargains
	Sonsi
	SPRichards
	StacksAndStacks
	Staples
	Tanga
	Target
	Target Plus
	TopHatter
	TradeMe
	uBid
	UnbeatableSale
	VendorCentral
	Walmart
	Walmart Marketplace
	Wayfair
	Website
	WFS
	Wholesale
	Wish
	Yahoo

')]</value>
      <webElementGuid>701b355c-56a0-4a01-9165-482d045ece30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
