<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Local_Store_Get</name>
   <tag></tag>
   <elementGuidId>2b0c7a65-98cd-4fba-b1ad-23f33fbcc709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_lblOrderSource</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_lblOrderSource']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be21b02c-514d-49c4-b818-22f15e7df6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_lblOrderSource</value>
      <webElementGuid>616ef822-55b8-4dcf-82c4-1c5a041113bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Local_Store</value>
      <webElementGuid>97a8ebb9-f42f-47e0-8acb-447e6da00024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_lblOrderSource&quot;)</value>
      <webElementGuid>c28a982e-068f-432f-82ce-db8e435a4a37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_lblOrderSource']</value>
      <webElementGuid>c071e3e2-fe8e-437d-85eb-4c53b6066435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_trMainRow']/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr[6]/td[2]/span</value>
      <webElementGuid>3d8b7aeb-f551-4e7d-a65b-cec21cfc6541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channel:'])[1]/following::span[1]</value>
      <webElementGuid>a91665bc-835d-4e90-a221-884dc2140e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='canada-comp'])[3]/following::span[1]</value>
      <webElementGuid>44c25ec4-7e31-40eb-9ef4-69f8d7e3b3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channel Order #:'])[1]/preceding::span[1]</value>
      <webElementGuid>9a752052-84f4-4e57-9713-4f953a0e84ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Sub Type:'])[1]/preceding::span[1]</value>
      <webElementGuid>034b7e58-7a5b-4220-a607-fec272d0a9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Local_Store']/parent::*</value>
      <webElementGuid>37fb44a0-9c5d-4075-9e2f-dd3e9687e4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/span</value>
      <webElementGuid>e10c86cf-b8e3-44fc-8cad-9c0436cfd920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_lblOrderSource' and (text() = 'Local_Store' or . = 'Local_Store')]</value>
      <webElementGuid>27a46919-942b-491b-9847-973177f60f15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
