<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LabelPaper_select</name>
   <tag></tag>
   <elementGuidId>9e2dcbaa-74ac-4a9a-9386-6f2a7af991ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_rdoLabelPaper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_rdoLabelPaper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16f4fd33-736d-40ab-b1e4-706aa4fe39ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_rdoLabelPaper</value>
      <webElementGuid>aecf84fc-ac04-43f6-8cb4-85985a3b2c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>576e15ab-a670-4293-9a28-6536e7b336e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$PrintUsing</value>
      <webElementGuid>03008462-af73-4fee-a1f9-43879123a210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdoLabelPaper</value>
      <webElementGuid>809bd88e-2711-4a9e-8a90-0dfc91c250b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>togglePrintLocation();</value>
      <webElementGuid>612bc70c-dbd7-4ff2-95fb-4b08ff5b2fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_rdoLabelPaper&quot;)</value>
      <webElementGuid>67ce704c-9866-4a7e-95a1-8e25363545d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_rdoLabelPaper']</value>
      <webElementGuid>8adfc5d0-b612-4eba-874b-c382f18fcc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trPrintUsingNormalMethod']/td/table/tbody/tr/td[2]/input[6]</value>
      <webElementGuid>dd2e2bba-84a3-4ee9-96e9-5b09064267f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>a9cfe21e-f19c-4455-bfbc-8176f888e43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_rdoLabelPaper' and @type = 'radio' and @name = 'ctl00$ContentPlaceHolder1$PrintUsing']</value>
      <webElementGuid>126dcea8-fe74-48b4-8120-f0fb67576260</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
