<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Detailed_select</name>
   <tag></tag>
   <elementGuidId>eaf1e4f1-4aa1-4eb0-b964-c5379860c578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_rdoDetailed']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_rdoDetailed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a08eaa0-95b6-4198-b89e-d121ad4815ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_rdoDetailed</value>
      <webElementGuid>32b698d1-26ae-43e4-80d0-5b75c2abf2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>948efa2c-cea4-4593-b735-841eb9f77939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$PrintUsing</value>
      <webElementGuid>ddf83542-2798-471d-8539-d41ced5e3039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdoDetailed</value>
      <webElementGuid>487a2795-b2f2-4124-977a-499c4db9a9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>togglePrintLocation();</value>
      <webElementGuid>6eaec538-876c-4e53-9954-bd015333e922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_rdoDetailed&quot;)</value>
      <webElementGuid>bc74f66e-3834-414f-ab3f-b721f057ed41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_rdoDetailed']</value>
      <webElementGuid>c91902ce-0bb5-4062-9320-be6d0a601bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trPrintUsingNormalMethod']/td/table/tbody/tr/td[2]/input[5]</value>
      <webElementGuid>f91ce961-75c5-4977-be03-87c04be51150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[5]</value>
      <webElementGuid>f70f39d4-3594-4fdc-9d04-98ab41a9a456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_rdoDetailed' and @type = 'radio' and @name = 'ctl00$ContentPlaceHolder1$PrintUsing']</value>
      <webElementGuid>d38d75e7-3958-42b2-a127-2dcfb6aeb556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
