<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GTIN_select</name>
   <tag></tag>
   <elementGuidId>4b1a82c9-afa7-4f28-8589-17f5b3c14c3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_rdoGTIN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_rdoGTIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ce908f2-6e62-4870-b8b4-c6a3a656ed91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_rdoGTIN</value>
      <webElementGuid>2cb6dd32-d339-4547-9b4f-a8c7a406f861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5205e595-6c44-4e52-a511-71ade36003e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$PrintUsing</value>
      <webElementGuid>c6aed4b6-c8f6-42a0-9248-e7e739656705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdoGTIN</value>
      <webElementGuid>61e14907-f347-4a7d-aa6f-8e6df3e87cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>togglePrintLocation();</value>
      <webElementGuid>3e6dc883-f20c-435c-bda1-69ef0dfc44f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_rdoGTIN&quot;)</value>
      <webElementGuid>78a19dc5-4c07-419b-807e-47862e17678d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_rdoGTIN']</value>
      <webElementGuid>2dbde67a-47b2-460d-a3a9-d6d7adbcf0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trPrintUsingNormalMethod']/td/table/tbody/tr/td[2]/input[8]</value>
      <webElementGuid>9aab9fe6-ff30-4e6c-b5c0-3c0cd985c8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>52cf2f4f-5cd3-4663-839c-e908547eb3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_rdoGTIN' and @type = 'radio' and @name = 'ctl00$ContentPlaceHolder1$PrintUsing']</value>
      <webElementGuid>89326dbb-1306-4002-8282-4a6f2703116e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
