<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnProcessJob</name>
   <tag></tag>
   <elementGuidId>04daf813-7a1c-4762-996e-3be76b88dd7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91da0057-2d3d-4718-8efc-8390d097a210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d224d246-076b-469d-b2de-adfae188d247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ContentPlaceHolder1$ContentPlaceHolder1$QueuedJobDetail1$btnProcessJob</value>
      <webElementGuid>14dd4b93-6e10-439c-8f5c-be400a350c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Process Job</value>
      <webElementGuid>b8cb032d-855b-44ad-83d1-8a1e949028ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hideMe(this);</value>
      <webElementGuid>e25ba12d-8a8f-4cc0-86ab-d29505d92b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob</value>
      <webElementGuid>d4a1743c-3bde-4f85-bcfb-728557b5fef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob&quot;)</value>
      <webElementGuid>b6f52305-052e-4b6a-b71f-f4217b1c0d02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob']</value>
      <webElementGuid>819a457d-5394-4047-a7b4-b9b24a61dfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_trProcessJob']/td/input</value>
      <webElementGuid>1e9a398f-bff3-4a5c-bf0b-6a0359a92efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/div/table/tbody/tr/td/input</value>
      <webElementGuid>f08f0236-3084-4a9d-beb4-04de4f7988bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ctl00$ContentPlaceHolder1$ContentPlaceHolder1$QueuedJobDetail1$btnProcessJob' and @id = 'ContentPlaceHolder1_ContentPlaceHolder1_QueuedJobDetail1_btnProcessJob']</value>
      <webElementGuid>a6597dfa-72d1-444e-bf0f-33868ea85847</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
