<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ASIN_select</name>
   <tag></tag>
   <elementGuidId>860ff0d6-2871-4b92-8995-f8631d59cf0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_rdoPrintUsingASIN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_rdoPrintUsingASIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53189a64-dc20-4f8f-8a8e-364c70cdfce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_rdoPrintUsingASIN</value>
      <webElementGuid>f463da74-8aee-41b0-aa8c-602f3e3d7564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3f9f196a-920b-488f-adba-ca1ab3365133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$PrintUsing</value>
      <webElementGuid>b639ff65-22d8-4a83-9508-a1e9dc07989e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdoPrintUsingASIN</value>
      <webElementGuid>521c5ff1-6e70-4b28-980b-3fd57d945ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>togglePrintLocation();</value>
      <webElementGuid>092d2f33-a7d6-43f8-8e00-e013fd4c105e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_rdoPrintUsingASIN&quot;)</value>
      <webElementGuid>89d16992-cfd3-4a50-9306-54d0b1ad0770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_rdoPrintUsingASIN']</value>
      <webElementGuid>84f2a5c3-7baa-4132-9d88-2f31b54a56c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trPrintUsingNormalMethod']/td/table/tbody/tr/td[2]/input[4]</value>
      <webElementGuid>fb78486e-90a0-4970-9a84-3bd4067c29dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[4]</value>
      <webElementGuid>9bccf505-5ac3-4145-950f-9f71f3714ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_rdoPrintUsingASIN' and @type = 'radio' and @name = 'ctl00$ContentPlaceHolder1$PrintUsing']</value>
      <webElementGuid>a36b50ba-68b4-430f-8003-d142ae2a9981</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
