<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SKU_select</name>
   <tag></tag>
   <elementGuidId>0c16dbb9-35ba-4565-b015-7d35f6232314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_rdoPrintUsingSKU']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_rdoPrintUsingSKU</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4925b7d7-62b4-471c-96df-8722a6eefb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_rdoPrintUsingSKU</value>
      <webElementGuid>cf54b074-788e-484e-908b-b6137c5766c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>64df9127-7db5-469c-b985-fd68055b7ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$PrintUsing</value>
      <webElementGuid>f74e0430-ddfc-49d5-87dd-2a4b3644c483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rdoPrintUsingSKU</value>
      <webElementGuid>bc625a21-8eaa-434d-a154-2208cddcdbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>45314218-a748-4057-b7cd-b2a211704f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>togglePrintLocation();</value>
      <webElementGuid>f7852c63-f5fd-46c1-bf67-604ecb57939b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_rdoPrintUsingSKU&quot;)</value>
      <webElementGuid>867896cb-b405-44ee-9ef1-35e9120b7471</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_rdoPrintUsingSKU']</value>
      <webElementGuid>1994c206-74ab-4c4e-aad4-f0c990b89a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trPrintUsingNormalMethod']/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>b512b931-d961-4a6b-b180-c2ee589bb7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>f501da47-2d00-4ed0-be6e-8f4a5a48b396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContentPlaceHolder1_rdoPrintUsingSKU' and @type = 'radio' and @name = 'ctl00$ContentPlaceHolder1$PrintUsing' and @checked = 'checked']</value>
      <webElementGuid>3b01570c-a219-4032-a24c-6569aec1a478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
