<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Get_OrderTotal</name>
   <tag></tag>
   <elementGuidId>34016f09-df4b-4801-a13b-76996b4fb6ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_GrandTotalField']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_GrandTotalField</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9086f88b-c364-4d30-a972-3134d97fb1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_GrandTotalField</value>
      <webElementGuid>f6cdd69d-ba7e-4f00-9ac9-1476cc33e87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C$26.50</value>
      <webElementGuid>6815ed5e-3efd-44d8-9a45-86ab729598b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_GrandTotalField&quot;)</value>
      <webElementGuid>a0e9c074-bf9e-4edb-af2c-4f05c74e216c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_GrandTotalField']</value>
      <webElementGuid>86378fd3-da12-44a5-94ff-980d4c3396a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/table/tbody/tr[4]/td[2]/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr[5]/td/table/tbody/tr/td[4]/table/tbody/tr[12]/td[2]/b/span</value>
      <webElementGuid>28026451-4dfa-4e26-af2a-15fc6a40d95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Total:'])[1]/following::span[1]</value>
      <webElementGuid>d2b32850-12fb-4734-88ac-c338df46738c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C$0.00'])[17]/following::span[1]</value>
      <webElementGuid>9be93829-6c71-4007-9b6d-72e97c7403d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Service:'])[1]/preceding::span[1]</value>
      <webElementGuid>95078dbd-6211-41c0-8fb9-2a12440070f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NoActionNeeded'])[1]/preceding::span[1]</value>
      <webElementGuid>79813d4b-6385-443e-9fb5-5c17a7edbfdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b/span</value>
      <webElementGuid>5592ddfa-20e6-43c3-9e2f-9b1e5f36af40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ContentPlaceHolder1_GrandTotalField' and (text() = 'C$26.50' or . = 'C$26.50')]</value>
      <webElementGuid>21e94cd9-f727-4dfc-b298-1f499051777c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
