<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UnitPriceProduct</name>
   <tag></tag>
   <elementGuidId>3a8502c1-085c-4b0c-a539-f5ae83e6a7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a17893ea-62b4-4cd4-bd73-2379564611ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl04$txtPrice</value>
      <webElementGuid>b0158683-db34-405b-9ff2-bea24fb2bf3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4166c10-9f1b-4ec1-a258-5148176588ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f38f6e88-6718-44c2-8b58-2e478616e5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice</value>
      <webElementGuid>fe502f60-9bae-4788-8b9f-2de69f4bbd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>adjustSubtotal('ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice', 'ContentPlaceHolder1_grdMain_ctl00_ctl04_txtQty', 'ContentPlaceHolder1_grdMain_ctl00_ctl04_lblSubTotal');</value>
      <webElementGuid>67b4d0dc-dcb6-4f8b-95a9-b2d0b358dd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice&quot;)</value>
      <webElementGuid>6b20fb7f-7128-4f27-ba80-f0afdaba14f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice']</value>
      <webElementGuid>7bd43dde-ac14-4ac6-80fc-17112c5a0e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContentPlaceHolder1_grdMain_ctl00__0']/td[5]/input</value>
      <webElementGuid>7c2bcf43-ae38-47ca-8af0-b124d3e1419b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/table/tbody/tr/td[5]/input</value>
      <webElementGuid>93097096-f600-4c99-8499-d9b51f716770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$grdMain$ctl00$ctl04$txtPrice' and @type = 'text' and @id = 'ContentPlaceHolder1_grdMain_ctl00_ctl04_txtPrice']</value>
      <webElementGuid>74c2a569-a85c-4a04-bc8e-7a7618f86734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
