<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnCreateOrder_SaveOrder</name>
   <tag></tag>
   <elementGuidId>bd351108-bbd0-4872-a423-55df95734287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_btnCreateOrder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContentPlaceHolder1_btnCreateOrder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13bd4232-900a-4fea-9cbb-54adec59df1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>52d9ddf9-afaf-4200-8a2a-156e3edd9fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$btnCreateOrder</value>
      <webElementGuid>ad038996-74af-480b-9cb0-5ad07580b1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_btnCreateOrder</value>
      <webElementGuid>d533ac33-657f-4e9b-add9-49af89b25109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/app/SaveOrder.jpg</value>
      <webElementGuid>4bf52778-f9c1-4411-8f55-afc7509da322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hideButtons();</value>
      <webElementGuid>d6cbe77a-68a7-4151-9f9a-828b6c0c916c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_btnCreateOrder&quot;)</value>
      <webElementGuid>f62ca5d0-2826-473f-979a-a4722d70832a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContentPlaceHolder1_btnCreateOrder']</value>
      <webElementGuid>e8c85050-252e-4198-bd78-2bcd9fb5f9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_pnlCreateOrder']/table/tbody/tr[7]/td/input</value>
      <webElementGuid>02d126ce-7358-40f9-9403-e942072a0c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/input</value>
      <webElementGuid>fa20913d-5873-446f-b14b-b731a308cadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$ContentPlaceHolder1$btnCreateOrder' and @id = 'ContentPlaceHolder1_btnCreateOrder' and @src = '/images/app/SaveOrder.jpg']</value>
      <webElementGuid>9301c043-6ed0-41bd-9d6a-e2e6548f7d42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
