<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Settings</name>
   <tag></tag>
   <elementGuidId>d858ef94-cc66-4320-874b-35a4b2ea9ad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mnuMainSettings']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mnuMainSettings</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2fc77aa1-91bb-43e1-b20a-95a3c042be27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rmLink rmRootLink rmExpanded</value>
      <webElementGuid>43d60b38-ce4e-4c24-851d-48454bb4c16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mnuMainSettings</value>
      <webElementGuid>d23657bf-d587-44b4-82e6-0f4ad1d40f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../Settings/default.aspx</value>
      <webElementGuid>588b7172-efeb-4c4e-afa1-f8bbb686f5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>fefa3fb0-b4e6-4290-8be8-f0ac56de9b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mnuMainSettings&quot;)</value>
      <webElementGuid>34f2c779-2b29-45e7-91b2-31707930190f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mnuMainSettings']</value>
      <webElementGuid>8616a4c2-aa5c-44b4-afa1-d35cdbb7866e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mnyMain']/ul/li[7]/a</value>
      <webElementGuid>9566ffe7-36c4-4baf-a662-41c10994951d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access List'])[1]/following::a[1]</value>
      <webElementGuid>355a88b7-8e2f-4549-9720-ed802e6466f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Employee'])[1]/following::a[2]</value>
      <webElementGuid>1f48fb95-869c-4be1-ad25-02568dcad77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Settings'])[1]/preceding::a[1]</value>
      <webElementGuid>7b549f3f-590f-4aba-b613-03dd2e69da48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../Settings/default.aspx')]</value>
      <webElementGuid>f3969680-a331-44d9-a8a8-3cc03b4425b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>59546163-27f2-486b-aa6e-f661443e432f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'mnuMainSettings' and @href = '../Settings/default.aspx' and (text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>71ef5af3-a31b-455f-a371-728b7b93a1fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
